<a href="https://colab.research.google.com/github/manishaachary13/Alma_study/blob/main/module2_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
# Create a Pandas DataFrame
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]})
print(df)

[1 2 3 4 5]
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [ ]:
arr=np.random.randint(1,50,10)
print(arr)
arr_sort=np.sort(arr)
print(arr_sort)
arr_sum=np.sum(arr)
print("sum=",arr_sum)
arr_mean=np.mean(arr)
print("mean=",arr_mean)


[27 14 42 38 14 29  9 29 20 37]
[ 9 14 14 20 27 29 29 37 38 42]
sum= 259
mean= 25.9


In [ ]:
arr_std=np.std(arr)
print(arr_std)

10.737318100903968


In [ ]:
zeros_array = np.zeros((3, 3))
ones_array = np.ones((2, 2))
print(zeros_array)
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
range_array = np.arange(0, 11, 2)
print("arrange:",range_array)
shape = arr.shape
print("shape:",shape)
print("arr=",arr)
reshaped_arr = arr.reshape((2, 5))
print("reshape:",reshaped_arr)

arrange: [ 0  2  4  6  8 10]
shape: (10,)
arr= [27 14 42 38 14 29  9 29 20 37]
reshape: [[27 14 42 38 14]
 [29  9 29 20 37]]


In [ ]:
transposed_arr = np.transpose(arr)
print("transpose:",transposed_arr)
dot_product = np.dot(arr, transposed_arr)
print("dot_product:",dot_product)

transpose: [27 14 42 38 14 29  9 29 20 37]
dot_product: 7861


In [ ]:
random_numbers = np.random.rand(3, 3)
random_normal_numbers = np.random.randn(2, 2)
print(random_numbers)
print(random_normal_numbers)

[[0.62831029 0.93524962 0.58388921]
 [0.64990739 0.0145599  0.64299047]
 [0.09303891 0.78296671 0.91865689]]
[[0.18959658 1.91155852]
 [0.05935891 1.81439375]]


In [ ]:
import numpy as np

# Create an array
data = np.array([1, 2, 3, 4, 5])

# Randomly choose two elements with replacement
random_samples_with_replacement = np.random.choice(data, size=4, replace=False)

# Randomly choose three elements without replacement
random_samples_without_replacement = np.random.choice(data, size=3, replace=True)

print("With replacement:", random_samples_with_replacement)
print("Without replacement:", random_samples_without_replacement)


With replacement: [4 5 2 3]
Without replacement: [3 4 3]


In [ ]:
# flatten() is a method that can be used to convert a multi-dimensional array into a one-dimensional array.
# It returns a copy of the original array, with all of its dimensions flattened into a single dimension.
arr_flatten=random_numbers.flatten()
print(arr_flatten)

[0.62831029 0.93524962 0.58388921 0.64990739 0.0145599  0.64299047
 0.09303891 0.78296671 0.91865689]


In [ ]:
# Creating our first DataFrame
some_2D_array = np.random.randint(4, 6,(4,5))
first_dataframe = pd.DataFrame(some_2D_array , columns=['Akshay','Devashish','Divy','Monika','Mani'])
first_dataframe

Akshay  Devashish  Divy  Monika  Mani
0       4          5     4       4     5
1       4          4     4       5     5
2       4          4     5       5     5
3       4          4     4       5     4

In [ ]:
#mounting your drive, so that you can access the files there
#you'll receive a authentication prompt. Complete it.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

# Create dummy DataFrame
data = {'Column1': np.random.rand(10), 'Column2': np.random.randint(1, 100, 10)}
df = pd.DataFrame(data)
print(df)
# Save DataFrame to CSV
df.to_csv('dummy_data.csv')


    Column1  Column2
0  0.724330        8
1  0.020730       90
2  0.706418       78
3  0.594126       64
4  0.025084       92
5  0.686799       58
6  0.434882       19
7  0.921981       23
8  0.655784       95
9  0.264841       64


In [ ]:
#file_path = #Make sure you've uploaded the imdb dataset onto your drive. Enter the file path of imdb dataset as a string here.
#imdb_df=pd.read_csv(file_path)
# OR
dummy_data = pd.read_csv('dummy_data.csv')
dummy_data.head()

Unnamed: 0   Column1  Column2
0           0  0.724330        8
1           1  0.020730       90
2           2  0.706418       78
3           3  0.594126       64
4           4  0.025084       92

🔍 **Scenario:**
You work for a company that sells fruits and vegetables. Your boss wants to know the average price and total sales of all the fruits they sold last month. Your task is to analyze the data and provide the required information.

In [ ]:
import numpy as np
fruits = np.array(["Apple", "Banana", "Cherry", "Dragonfruit", "Elderberry"])
quantity_sold = np.array([100, 200, 50, 75, 150])
price_per_unit = np.array([0.5, 0.25, 1, 1.5, 2])
# calculate avg price and total sales of last month
avg_price = np.mean(price_per_unit)
total_sales = np.sum(price_per_unit * quantity_sold)
print("Average price:", avg_price)
print("Total sales:", total_sales)

Average price: 1.05
Total sales: 562.5


🔍 Scenario:
You work for a company that sells various products. Your boss wants to know some statistical information about the sales of the products. Your task is to analyze the data and provide the required information:

1. Mean sales.
2. Median sales.
3. Mode of Sales.
4. Standard Deviation.
5. Variance.

In [ ]:
# 📊 Dataset:
sales = np.array([100, 200, 150, 75, 250, 300, 175, 225, 125, 275])
# Hint : - In order to derive othere statistic measures,
# we will have to make use of an additional library. Let's import scipy library for this. Use
from scipy import stats

#What is the mean, median, mode, standard deviation, and variance of the sales data?
prod_mean=np.mean(sales)
print("Mean=",prod_mean)
prod_median=np.median(sales)
print("Mrdian=",prod_median)
prod_mode=stats.mode(sales)
print(prod_mode)
prod_std=np.std(sales)
print("Standard deviationm:",prod_std)
prod_var=np.var(sales)
print("variance:",prod_var)

Mean= 187.5
Mrdian= 187.5
ModeResult(mode=75, count=1)
Standard deviationm: 71.80703308172536
variance: 5156.25


In [ ]:
# 📊 Dataset
num_layers = 4
num_features = 6
min_value = 0
max_value = 255
design = np.linspace(min_value, max_value, num=num_layers * num_features).reshape(num_layers, num_features)
np.set_printoptions(precision=3, suppress=True)
print(design)

[[  0.     11.087  22.174  33.261  44.348  55.435]
 [ 66.522  77.609  88.696  99.783 110.87  121.957]
 [133.043 144.13  155.217 166.304 177.391 188.478]
 [199.565 210.652 221.739 232.826 243.913 255.   ]]


In [ ]:
# Import pandas
import pandas as pd

# Create dictionary containing information about the books
books_dict = {
    'Title': ['Book A', 'Book B', 'Book C', 'Book D', 'Book E'],
    'Author': ['Author X', 'Author Y', 'Author X', 'Author Z', 'Author Y'],
    'Year of Publication': [2005, 2010, 2002, 2015, 2018],
    'Number of Pages': [300, 250, 180, 400, 320]
}

# Create DataFrame from dictionary
books=pd.DataFrame(books_dict)

# Print entire DataFrame
print(books)

# Print first five rows of DataFrame
print("First five:",books[:5])

# Print last three rows of DataFrame
print("Last three:",books[-4:-1])

# Sort DataFrame by year of publication in ascending order
book_sort=books.sort_values('Year of Publication', ascending=True)
print("Sorted by year:",book_sort)

# Sort DataFrame by number of pages in descending order
page_sort=books.sort_values('Number of Pages',ascending=False)
print("Sort by pages:",page_sort)

# Filter DataFrame to show only books published after the year 2000
book_after_2005=books[books['Year of Publication']>2005]
print("Books after 2005:",book_after_2005)

# Calculate the average number of pages for all books in the DataFrame
average_pages=books['Number of Pages'].mean()
print("average_number_of_pages",average_pages)
# Group DataFrame by author, and calculate total number of pages for each author



    Title    Author  Year of Publication  Number of Pages
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320
First five:     Title    Author  Year of Publication  Number of Pages
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320
Last three:     Title    Author  Year of Publication  Number of Pages
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
Sorted by year:     Title    Author  Year of Pub

In [ ]:
# This example shows how to access the DataFrame with a boolean index:

# importing pandas as pd
import pandas as pd
# dictionary of lists
dict = {'name':["Smith", "William", "Phill", "Parker"],
        'age': ["28", "39", "34", "36"]}
info = pd.DataFrame(dict, index = [True, True, False, True])
print(info)

          name age
True     Smith  28
True   William  39
False    Phill  34
True    Parker  36


In [ ]:
#The .loc[] function in Pandas is a powerful method for accessing a group of rows and columns by labels or a boolean array.
# It is primarily label-based, but may also be used with boolean conditions.
#  This example shows how to access the DataFrame with a boolean index by using .loc[]

# importing pandas as pd
import pandas as pd
# dictionary of lists
dict = {'name':["Smith", "William", "Phill", "Parker"],
        'age': ["28", "39", "34", "36"]}
info = pd.DataFrame(dict, index = [True, True, False, True])
# accessing a dataframe using .loc[] function
print(info.loc[True])

         name age
True    Smith  28
True  William  39
True   Parker  36


In [ ]:
import pandas as pd

# Creating a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Salary': [50000, 60000, 70000, 80000]}

df = pd.DataFrame(data, index=['A', 'B', 'C', 'D'])
print("data:",df)
# Using .loc[] to select data
selected_row = df.loc['B']
selected_rows = df.loc[['A', 'C']]
selected_data = df.loc[['B', 'D'], ['Name', 'Salary']]

print("Selected Row:")
print(selected_row)

print("\nSelected Rows:")
print(selected_rows)

print("\nSelected Data:")
print(selected_data)


data:       Name  Age  Salary
A    Alice   25   50000
B      Bob   30   60000
C  Charlie   35   70000
D    David   40   80000
Selected Row:
Name        Bob
Age          30
Salary    60000
Name: B, dtype: object

Selected Rows:
      Name  Age  Salary
A    Alice   25   50000
C  Charlie   35   70000

Selected Data:
    Name  Salary
B    Bob   60000
D  David   80000


In [ ]:
# numpy.reshape(a, newshape, order='C')
arr = np.arange(16).reshape(2, 8)
print("\nreshapedarray: \n", arr)
arr2d_1 = np.arange(10,19).reshape(3,3)
arr2d_1


reshapedarray: 
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
one = pd.DataFrame({'Name': ['Parker', 'Phill', 'Smith'],'id':[108,119,127]},index=['A','B','C'])
two = pd.DataFrame({'Name': ['Terry', 'Jones', 'John'],
                    'id':[102,125,112]},
index=['A','B','C'])
print(pd.concat([one,two]))
print()
print(pd.concat([one,two],keys=['x','y']))

     Name   id
A  Parker  108
B   Phill  119
C   Smith  127
A   Terry  102
B   Jones  125
C    John  112

       Name   id
x A  Parker  108
  B   Phill  119
  C   Smith  127
y A   Terry  102
  B   Jones  125
  C    John  112


In [ ]:
# Python Program for Pandas datetime Library
import pandas as pd
# Create a DataFrame with 'year', 'month', and 'day' columns
info = pd.DataFrame({'year': [2014, 2012],
'month': [5, 7],
'day': [20, 17]},index=[1,2])

# Convert the DataFrame columns to datetime format
pd.to_datetime(info)

1   2014-05-20
2   2012-07-17
dtype: datetime64[ns]

In [ ]:
start_date = '2017-06-04'
num_periods = 4
frequency = 'S'
dates = pd.date_range(start=start_date, periods=num_periods, freq=frequency)
# Display the generated sequence of dates
dates

DatetimeIndex(['2017-06-04 00:00:00', '2017-06-04 00:00:01',
               '2017-06-04 00:00:02', '2017-06-04 00:00:03'],
              dtype='datetime64[ns]', freq='S')

In [ ]:
# Create a sample DataFrame with datetime index
data = {'Value': [10, 15, 8, 12, 9]}
index = pd.date_range('2022-01-01', periods=5, freq='D')
df = pd.DataFrame(data, index=index)

# Perform rolling window calculation on the 'Value' column
rolling_mean = df['Value'].rolling(window=2).mean()

# Print the DataFrame and rolling mean values
print("DataFrame:")
print(df)
print("Rolling Mean:")
print(rolling_mean)

DataFrame:
            Value
2022-01-01     10
2022-01-02     15
2022-01-03      8
2022-01-04     12
2022-01-05      9
Rolling Mean:
2022-01-01     NaN
2022-01-02    12.5
2022-01-03    11.5
2022-01-04    10.0
2022-01-05    10.5
Freq: D, Name: Value, dtype: float64


In [ ]:
import numpy as np
np.__version__
# '1.12.1'

'1.23.5'

In [ ]:
L = list(range(10))
[type(item) for item in L]
#creating arrays
print("Zeros:",np.zeros(10, dtype='int'))


#creating a 3 row x 5 column matrix
print("Ones:",np.ones((3,5), dtype=float))

#creating a matrix with a predefined value
print("Full:",np.full((3,5),1.23))


#create an array with a set sequence
print("Arrange:",np.arange(0, 20, 2))


#create an array of even space between the given range of values
print("Linspace:",np.linspace(0, 1, 5))


#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0, 1, (3,3))

print(np.eye(3))

Zeros: [0 0 0 0 0 0 0 0 0 0]
Ones: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full: [[1.23 1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23 1.23]]
Arrange: [ 0  2  4  6  8 10 12 14 16 18]
Linspace: [0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1hSW3BnrsIO_4KuB5Te6EEEI-ctWDEzTy%2Fview

In [ ]:
# import modules
from google.colab import drive
import pandas as pd
import numpy as np
# mounting drive
drive.mount('/content/drive')
path='/content/drive/MyDrive/Colab Notebooks/imdb_data.csv'

imdb_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/imdb_data.csv')
imdb_df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


id                              belongs_to_collection    budget  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2        3                                                NaN   3300000   
3        4                                                NaN   1200000   
4        5                                                NaN         0   
...    ...                                                ...       ...   
2995  2996                                                NaN         0   
2996  2997                                                NaN         0   
2997  2998                                                NaN  65000000   
2998  2999                                                NaN  42000000   
2999  3000                                                NaN  35000000   

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]   
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                         [{'id': 18, 'name': 'Drama'}]   
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   
...                                                 ...   
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                               homepage    imdb_id original_language  \
0                                   NaN  tt2637294                en   
1                                   NaN  tt0368933                en   
2     http://sonyclassics.com/whiplash/  tt2582802                en   
3            http://kahaanithefilm.com/  tt1821480                hi   
4                                   NaN  tt1380152                ko   
...                                 ...        ...               ...   
2995                                NaN  tt0109403                en   
2996                                NaN  tt2364975                sv   
2997                                NaN  tt0116908                en   
2998     http://www.alongcamepolly.com/  tt0343135                en   
2999   http://www.abductionthefilm.com/  tt1600195                en   

                                original_title  \
0                       Hot Tub Time Machine 2   
1     The Princess Diaries 2: Royal Engagement   
2                                     Whiplash   
3                                      Kahaani   
4                                         마린보이   
...                                        ...   
2995                                   Chasers   
2996                               Vi är bäst!   
2997                   The Long Kiss Goodnight   
2998                          Along Came Polly   
2999                                 Abduction   

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...   
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2     Under the direction of a ruthless instructor, ...   64.299990  ...   
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4     Marine Boy is the story of a former national s...    1.148070  ...   
...                                                 ...         ...  ...   
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     release_date r

In [ ]:
imdb_df.head(5)     #Prints the first  n  rows of the dataframe. By default it prints the first 5 rows
imdb_df.tail(5)     #Prints the last  n  rows of the dataframe. By default it prints the last 5 rows

id belongs_to_collection    budget  \
2995  2996                   NaN         0   
2996  2997                   NaN         0   
2997  2998                   NaN  65000000   
2998  2999                   NaN  42000000   
2999  3000                   NaN  35000000   

                                                 genres  \
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                              homepage    imdb_id original_language  \
2995                               NaN  tt0109403                en   
2996                               NaN  tt2364975                sv   
2997                               NaN  tt0116908                en   
2998    http://www.alongcamepolly.com/  tt0343135                en   
2999  http://www.abductionthefilm.com/  tt1600195                en   

               original_title  \
2995                  Chasers   
2996              Vi är bäst!   
2997  The Long Kiss Goodnight   
2998         Along Came Polly   
2999                Abduction   

                                               overview  popularity  ...  \
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     release_date runtime                          spoken_languages    status  \
2995      4/22/94   102.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2996      3/28/13   102.0  [{'iso_639_1': 'sv', 'name': 'svenska'}]  Released   
2997     10/11/96   120.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2998      1/16/04    90.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2999      9/22/11   106.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                                tagline  \
2995  It was supposed to be a routine prisoner trans...   
2996                                                NaN   
2997               What's forgotten is not always gone.   
2998  For the most cautious man on Earth, life is ab...   
2999          They stole his life. He's taking it back.   

                        title  \
2995                  Chasers   
2996         We Are the Best!   
2997  The Long Kiss Goodnight   
2998         Along Came Polly   
2999                Abduction   

                                               Keywords  \
2995  [{'id': 378, 'name': 'prison'}, {'id': 572, 'n...   
2996  [{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...   
2997  [{'id': 441, 'name': 'assassination'}, {'id': ...   
2998  [{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...   
2999  [{'id': 591, 'name': 'cia'}, {'id': 822, 'name...   

                                                   cast  \
2995  [{'cast_id': 2, 'character': 'Rock Reilly', 'c...   
2996  [{'cast_id': 5, 'character': 'Bobo', 'credit_i...   
2997  [{'cast_id': 10, 'character': 'Samantha Caine ...   
2998  [{'cast_id': 8, 'character': 'Reuben Feffer', ...   
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...   

                                                   crew    revenue  
2995  [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...    1596687  
2996  [{'credit_id': '5716b72ac3a3686678012c84', 'de...     180590  
2997  [{'credit_id': '52fe443a9251416c7502d579', 'de...   89456761  
2998  [{'credit_id': '556f817b9251410866000a63', 'de...  171963386  
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...   82087155  

[5 rows x 23 columns]

In [ ]:
imdb_df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
data=imdb_df[['id','imdb_id', 'belongs_to_collection', 'original_language', 'original_title','production_countries','status', 'tagline',]]
data


id    imdb_id                              belongs_to_collection  \
0        1  tt2637294  [{'id': 313576, 'name': 'Hot Tub Time Machine ...   
1        2  tt0368933  [{'id': 107674, 'name': 'The Princess Diaries ...   
2        3  tt2582802                                                NaN   
3        4  tt1821480                                                NaN   
4        5  tt1380152                                                NaN   
...    ...        ...                                                ...   
2995  2996  tt0109403                                                NaN   
2996  2997  tt2364975                                                NaN   
2997  2998  tt0116908                                                NaN   
2998  2999  tt0343135                                                NaN   
2999  3000  tt1600195                                                NaN   

     original_language                            original_title  \
0                   en                    Hot Tub Time Machine 2   
1                   en  The Princess Diaries 2: Royal Engagement   
2                   en                                  Whiplash   
3                   hi                                   Kahaani   
4                   ko                                      마린보이   
...                ...                                       ...   
2995                en                                   Chasers   
2996                sv                               Vi är bäst!   
2997                en                   The Long Kiss Goodnight   
2998                en                          Along Came Polly   
2999                en                                 Abduction   

                                   production_countries    status  \
0     [{'iso_3166_1': 'US', 'name': 'United States o...  Released   
1     [{'iso_3166_1': 'US', 'name': 'United States o...  Released   
2     [{'iso_3166_1': 'US', 'name': 'United States o...  Released   
3               [{'iso_3166_1': 'IN', 'name': 'India'}]  Released   
4         [{'iso_3166_1': 'KR', 'name': 'South Korea'}]  Released   
...                                                 ...       ...   
2995  [{'iso_3166_1': 'US', 'name': 'United States o...  Released   
2996  [{'iso_3166_1': 'DK', 'name': 'Denmark'}, {'is...  Released   
2997  [{'iso_3166_1': 'US', 'name': 'United States o...  Released   
2998  [{'iso_3166_1': 'US', 'name': 'United States o...  Released   
2999  [{'iso_3166_1': 'US', 'name': 'United States o...  Released   

                                                tagline  
0     The Laws of Space and Time are About to be Vio...  
1     It can take a lifetime to find true love; she'...  
2       The road to greatness can take you to the edge.  
3                                                   NaN  
4                                                   NaN  
...                                                 ...  
2995  It was supposed to be a routine prisoner trans...  
2996                                                NaN  
2997               What's forgotten is not always gone.  
2998  For the most cautious man on Earth, life is ab...  
2999          They stole his life. He's taking it back.  

[3000 rows x 8 columns]

In [ ]:
list(imdb_df.columns)

['id',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'Keywords',
 'cast',
 'crew',
 'revenue']

In [ ]:
# Prints the basic information about our dataframe
imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     3000 non-null   int64  
 1   belongs_to_collection  604 non-null    object 
 2   budget                 3000 non-null   int64  
 3   genres                 2993 non-null   object 
 4   homepage               946 non-null    object 
 5   imdb_id                3000 non-null   object 
 6   original_language      3000 non-null   object 
 7   original_title         3000 non-null   object 
 8   overview               2992 non-null   object 
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object 
 11  production_companies   2844 non-null   object 
 12  production_countries   2945 non-null   object 
 13  release_date           3000 non-null   object 
 14  runtime                2998 non-null   float64
 15  spok

In [ ]:
imdb_df.rename(columns={'spoken_language':'using_language'},inplace=True)
imdb_df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

📈🔍 The describe method in Pandas is like having a personal statistician for your dataset! It provides a summary of the most important information, including the count, mean, standard deviation, minimum, maximum, and percentiles. All this without having to do any math yourself! Plus, it automatically excludes any NaN values so you don't have to worry about them. This makes it a great tool for getting a quick and comprehensive overview of your data's distribution, spotting any outliers or patterns, and making informed decisions.

In [ ]:
imdb_df.describe()

id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [ ]:
working_dir_path= '/var/my_works'
imdb_df.to_csv(working_dir_path +'output_imdb.csv')

#your dataframe would be saved as "output_imdb"

In [ ]:
imdb_df.sort_values('imdb_id',ascending=True).tail(10)

id                              belongs_to_collection    budget  \
1589  1590                                                NaN         0   
224    225                                                NaN         0   
1694  1695                                                NaN    521873   
1522  1523                                                NaN         0   
1756  1757                                                NaN         0   
2436  2437                                                NaN   4300000   
2489  2490  [{'id': 86110, 'name': 'Diary of a Wimpy Kid C...  22000000   
1202  1203                                                NaN         0   
496    497                                                NaN   2800000   
391    392                                                NaN   7075038   

                                                 genres  \
1589                      [{'id': 18, 'name': 'Drama'}]   
224                      [{'id': 35, 'name': 'Comedy'}]   
1694  [{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...   
1522  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...   
1756  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...   
2436  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...   
2489  [{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...   
1202                     [{'id': 28, 'name': 'Action'}]   
496   [{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...   
391   [{'id': 12, 'name': 'Adventure'}, {'id': 18, '...   

                            homepage    imdb_id original_language  \
1589                             NaN  tt5655222                en   
224       http://www.garygulman.com/  tt5661030                en   
1694                             NaN  tt5662932                hi   
1522                             NaN  tt5789664                ru   
1756  http://www.linewalkermovie.com  tt5896962                cn   
2436                             NaN  tt5946128                hi   
2489                             NaN  tt6003368                en   
1202                             NaN  tt6201292                ta   
496     http://phoenixforgotten.com/  tt6574272                en   
391                              NaN  tt6673840                ru   

                           original_title  \
1589                             The Hero   
224          Gary Gulman: It's About Time   
1694                         रमन राघव २.०   
1522           Петербург. Только по любви   
1756                                 使徒行者   
2436                         Dear Zindagi   
2489  Diary of a Wimpy Kid: The Long Haul   
1202                                பைரவா   
496                     Phoenix Forgotten   
391                          Время первых   

                                               overview  popularity  ...  \
1589  Lee, a former Western film icon, is living a c...    6.549788  ...   
224   Netflix presents standup and two-time Last Com...    0.410738  ...   
1694  Set in present day Mumbai the story follows th...    1.668794  ...   
1522  Petersburg. A Selfie comprises seven novellas ...    0.780748  ...   
1756  The details of undercover police officers are ...    1.528202  ...   
2436  An unconventional thinker (Shah Rukh Khan) hel...    3.699552  ...   
2489  A Heffley family road trip to attend Meemaw's ...   28.176992  ...   
1202  A loan recovery agent takes on a corrupt head ...    1.459459  ...   
496   20 years after three teenagers disappeared in ...   12.560942  ...   
391   March 1965. In the heat of the Cold War, the U...   10.181000  ...   

     release_date runtime                                   spoken_languages  \
1589       6/9/17    97.0           [{'iso_639_1': 'en', 'name': 'English'}]   
224        5/1/16    53.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1694      6/24/16   127.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]   
1522      9/22/16   111.0           [{'iso_639_1': 'ru', 'name': 'Pусский'}]   
1756      8/11/16   108.0  [{'iso_639_1

In [ ]:
# Create a DataFrame
data = {'name': ['Alice', 'Bob', 'Charlie'],
        'age': [25, 30, 35]}
df = pd.DataFrame(data)

# Write the DataFrame to a CSV file
df.to_csv('/content/drive/MyDrive/Colab Notebooks/nameframe.csv', index=True)

#Check out the files tab on the left for the file.

In [ ]:
# Now let us subset our dataframe in which we want to have first 8 rows identified with their rows labels and some named columns
# this prints the data from index 50 to 80 with columns budget, begres and runtime
imdb_df.loc[50:80,['budget','genres','runtime']]

budget                                             genres  runtime
50     560000  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...    102.0
51   12000000  [{'id': 12, 'name': 'Adventure'}, {'id': 35, '...    160.0
52          0  [{'id': 12, 'name': 'Adventure'}, {'id': 10751...     97.0
53          0  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...     98.0
54   20000000                     [{'id': 28, 'name': 'Action'}]    107.0
55          0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...     95.0
56          0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...     97.0
57  125000000  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...    125.0
58          0  [{'id': 10402, 'name': 'Music'}, {'id': 10749,...     95.0
59   14000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...     95.0
60  150000000  [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...    144.0
61    4000000                      [{'id': 18, 'name': 'Drama'}]    105.0
62          0  [{'id': 53, 'name': 'Thriller'}, {'id': 14, 'n...    124.0
63    5000000  [{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...    100.0
64   12000000  [{'id': 18, 'name': 'Drama'}, {'id': 12, 'name...    115.0
65    1500000                     [{'id': 28, 'name': 'Action'}]     92.0
66   12000000  [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...    108.0
67          0                      [{'id': 18, 'name': 'Drama'}]    133.0
68    2000000  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...    129.0
69   85000000  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...    104.0
70   29000000  [{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...    103.0
71          0                      [{'id': 18, 'name': 'Drama'}]    126.0
72   11000000  [{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...     85.0
73          0  [{'id': 80, 'name': 'Crime'}, {'id': 99, 'name...     90.0
74     445000  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...     84.0
75   17000000  [{'id': 27, 'name': 'Horror'}, {'id': 35, 'nam...    106.0
76     500000  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...    157.0
77    6000000                     [{'id': 35, 'name': 'Comedy'}]     98.0
78          0  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...    122.0
79    1500000  [{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...    102.0
80   15000000  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...    118.0

In [ ]:
imdb_df.loc[:,['budget','genres','runtime','original_title']]

budget                                             genres  runtime  \
0     14000000                     [{'id': 35, 'name': 'Comedy'}]     93.0   
1     40000000  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...    113.0   
2      3300000                      [{'id': 18, 'name': 'Drama'}]    105.0   
3      1200000  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...    122.0   
4            0  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...    118.0   
...        ...                                                ...      ...   
2995         0  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...    102.0   
2996         0  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...    102.0   
2997  65000000  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...    120.0   
2998  42000000  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...     90.0   
2999  35000000  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...    106.0   

                                original_title  
0                       Hot Tub Time Machine 2  
1     The Princess Diaries 2: Royal Engagement  
2                                     Whiplash  
3                                      Kahaani  
4                                         마린보이  
...                                        ...  
2995                                   Chasers  
2996                               Vi är bäst!  
2997                   The Long Kiss Goodnight  
2998                          Along Came Polly  
2999                                 Abduction  

[3000 rows x 4 columns]

In [ ]:
imdb_df.loc[:,['budget', 'genres', 'runtime']]

budget                                             genres  runtime
0     14000000                     [{'id': 35, 'name': 'Comedy'}]     93.0
1     40000000  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...    113.0
2      3300000                      [{'id': 18, 'name': 'Drama'}]    105.0
3      1200000  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...    122.0
4            0  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...    118.0
...        ...                                                ...      ...
2995         0  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...    102.0
2996         0  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...    102.0
2997  65000000  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...    120.0
2998  42000000  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...     90.0
2999  35000000  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...    106.0

[3000 rows x 3 columns]

In [ ]:
# read all rows from last 3 columns
imdb_df.iloc[:,-3:]

cast  \
0     [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1     [{'cast_id': 1, 'character': 'Mia Thermopolis'...   
2     [{'cast_id': 5, 'character': 'Andrew Neimann',...   
3     [{'cast_id': 1, 'character': 'Vidya Bagchi', '...   
4     [{'cast_id': 3, 'character': 'Chun-soo', 'cred...   
...                                                 ...   
2995  [{'cast_id': 2, 'character': 'Rock Reilly', 'c...   
2996  [{'cast_id': 5, 'character': 'Bobo', 'credit_i...   
2997  [{'cast_id': 10, 'character': 'Samantha Caine ...   
2998  [{'cast_id': 8, 'character': 'Reuben Feffer', ...   
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...   

                                                   crew    revenue  
0     [{'credit_id': '59ac067c92514107af02c8c8', 'de...   12314651  
1     [{'credit_id': '52fe43fe9251416c7502563d', 'de...   95149435  
2     [{'credit_id': '54d5356ec3a3683ba0000039', 'de...   13092000  
3     [{'credit_id': '52fe48779251416c9108d6eb', 'de...   16000000  
4     [{'credit_id': '52fe464b9251416c75073b43', 'de...    3923970  
...                                                 ...        ...  
2995  [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...    1596687  
2996  [{'credit_id': '5716b72ac3a3686678012c84', 'de...     180590  
2997  [{'credit_id': '52fe443a9251416c7502d579', 'de...   89456761  
2998  [{'credit_id': '556f817b9251410866000a63', 'de...  171963386  
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...   82087155  

[3000 rows x 3 columns]

In [ ]:
imdb_df.iloc[ : 10,  : 4]
imdb_df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
# Boolean Indexing
english_movies = imdb_df.loc[:,'original_language']=='en'
english_movies.head(15)

0      True
1      True
2      True
3     False
4     False
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
Name: original_language, dtype: bool

In [ ]:
# adding new column
imdb_df.loc[:,'half_runtime']=imdb_df.loc[:,'runtime']*.5
imdb_df

id                              belongs_to_collection    budget  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2        3                                                NaN   3300000   
3        4                                                NaN   1200000   
4        5                                                NaN         0   
...    ...                                                ...       ...   
2995  2996                                                NaN         0   
2996  2997                                                NaN         0   
2997  2998                                                NaN  65000000   
2998  2999                                                NaN  42000000   
2999  3000                                                NaN  35000000   

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]   
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                         [{'id': 18, 'name': 'Drama'}]   
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   
...                                                 ...   
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                               homepage    imdb_id original_language  \
0                                   NaN  tt2637294                en   
1                                   NaN  tt0368933                en   
2     http://sonyclassics.com/whiplash/  tt2582802                en   
3            http://kahaanithefilm.com/  tt1821480                hi   
4                                   NaN  tt1380152                ko   
...                                 ...        ...               ...   
2995                                NaN  tt0109403                en   
2996                                NaN  tt2364975                sv   
2997                                NaN  tt0116908                en   
2998     http://www.alongcamepolly.com/  tt0343135                en   
2999   http://www.abductionthefilm.com/  tt1600195                en   

                                original_title  \
0                       Hot Tub Time Machine 2   
1     The Princess Diaries 2: Royal Engagement   
2                                     Whiplash   
3                                      Kahaani   
4                                         마린보이   
...                                        ...   
2995                                   Chasers   
2996                               Vi är bäst!   
2997                   The Long Kiss Goodnight   
2998                          Along Came Polly   
2999                                 Abduction   

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...   
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2     Under the direction of a ruthless instructor, ...   64.299990  ...   
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4     Marine Boy is the story of a former national s...    1.148070  ...   
...                                                 ...         ...  ...   
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     runtime       

In [ ]:
imdb_df['hrt'] = imdb_df['runtime'] * 0.5
imdb_df.drop('half_runtime', inplace= True , axis = 1)
imdb_df.head(2)

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   

                                              genres homepage    imdb_id  \
0                     [{'id': 35, 'name': 'Comedy'}]      NaN  tt2637294   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...      NaN  tt0368933   

  original_language                            original_title  \
0                en                    Hot Tub Time Machine 2   
1                en  The Princess Diaries 2: Royal Engagement   

                                            overview  popularity  ... runtime  \
0  When Lou, who has become the "father of the In...    6.575393  ...    93.0   
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...   113.0   

                           spoken_languages    status  \
0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                             tagline  \
0  The Laws of Space and Time are About to be Vio...   
1  It can take a lifetime to find true love; she'...   

                                      title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...   

                                                crew   revenue   hrt  
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651  46.5  
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435  56.5  

[2 rows x 24 columns]

imdb_df: This suggests that you have a DataFrame named imdb_df. DataFrames are two-dimensional tabular data structures in pandas.

.drop('half_runtime', inplace=True, axis=1): This is calling the drop method on the DataFrame. Here's what each part does:

'half_runtime': This is the label of the column you want to drop. In this case, it's 'half_runtime'.

inplace=True: This parameter is set to True, which means that the operation will be done in place, and the DataFrame imdb_df will be modified directly. If inplace is set to False or omitted, a new DataFrame with the specified column removed will be returned.

axis=1: This parameter specifies that you're dropping a column (as opposed to a row). The value 1 refers to columns; 0 would refer to rows.

So, the line of code is effectively removing the 'half_runtime' column from the DataFrame imdb_df in place.

In [ ]:
# movie_profit=revenue-budget
imdb_df.loc[:,'movie_profit']= imdb_df.loc[:,'revenue'] - imdb_df.loc[:,'budget']
imdb_df.head()

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2   3                                                NaN   3300000   
3   4                                                NaN   1200000   
4   5                                                NaN         0   

                                              genres  \
0                     [{'id': 35, 'name': 'Comedy'}]   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                      [{'id': 18, 'name': 'Drama'}]   
3  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   

                            homepage    imdb_id original_language  \
0                                NaN  tt2637294                en   
1                                NaN  tt0368933                en   
2  http://sonyclassics.com/whiplash/  tt2582802                en   
3         http://kahaanithefilm.com/  tt1821480                hi   
4                                NaN  tt1380152                ko   

                             original_title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                      마린보이   

                                            overview  popularity  ...  \
0  When Lou, who has become the "father of the In...    6.575393  ...   
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2  Under the direction of a ruthless instructor, ...   64.299990  ...   
3  Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4  Marine Boy is the story of a former national s...    1.148070  ...   

                                    spoken_languages    status  \
0           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
3  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released   
4           [{'iso_639_1': 'ko', 'name': '한국어/조선말'}]  Released   

                                             tagline  \
0  The Laws of Space and Time are About to be Vio...   
1  It can take a lifetime to find true love; she'...   
2    The road to greatness can take you to the edge.   
3                                                NaN   
4                                                NaN   

                                      title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                Marine Boy   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...   
2  [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...   
3  [{'id': 10092, 'name': 'mystery'}, {'id': 1054...   
4                                                NaN   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...   
2  [{'cast_id': 5, 'character': 'Andrew Neimann',...   
3  [{'cast_id': 1, 'character': 'Vidya Bagchi', '...   
4  [{'cast_id': 3, 'character': 'Chun-soo', 'cred...   

                                                crew   revenue   hrt  \
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651  46.5   
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435  56.5   
2  [{'credit_id': '54d5356ec3a3683ba0000039', 'de...  13092000  52.5   
3  [{'credit_id': '52fe48779251416c9108d6eb', 'de...  16000000  61.0   
4  [{'credit_id': '52fe464b9251416c75073b43', 'de...   39

In [ ]:
# remove or drop poster_path column from csv file
imdb_df.drop('overview',inplace=True, axis=1)
imdb_df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'runtime', 'spoken_languages', 'status', 'tagline',
       'title', 'Keywords', 'cast', 'crew', 'revenue', 'hrt', 'movie_profit'],
      dtype='object')



```
1.   dropna()         11.read_csv()
2.   fillna()         12.head()
3.   replace()        13.tail()
4.   loc()            14.info()
5.   iloc()           15.describe()
6.   merge()          16.shape()
7.   concat()         17.columns
8.   mean()           18.pivot_table()
9.   sum()
10.  groupby
```

     





```
| Function   | Syntax                                                                                             |
|------------|----------------------------------------------------------------------------------------------------|
| `dropna()` | `DataFrame.dropna(axis=0, how='any', subset=None, inplace=False)`                                  |
| `fillna()` | `DataFrame.fillna(value=None, method=None, axis=None, inplace=False)`                               |
| `replace()`| `DataFrame.replace(to_replace=None, value=None, inplace=False, limit=None)`                         |
| `loc()`    | `DataFrame.loc[row_indexer, column_indexer]`                                                       |
| `iloc()`   | `DataFrame.iloc[row_indexer, column_indexer]`                                                      |
| `merge()`  | `pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None)`                          |
| `concat()` | `pd.concat(objs, axis=0, join='outer', ignore_index=False)`                                        |
| `mean()`   | `DataFrame.mean(axis=None, skipna=None, level=None, numeric_only=None)`                             |
| `sum()`    | `DataFrame.sum(axis=None, skipna=None, level=None, numeric_only=None)`                              |
| `groupby()`| `DataFrame.groupby(by=None, axis=0, level=None, ...)`                                              |
| `read_csv()`| `pd.read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, ...)`        |
| `head()`   | `DataFrame.head(n=5)`                                                                              |
| `tail()`   | `DataFrame.tail(n=5)`                                                                              |
| `info()`   | `DataFrame.info()`                                                                                |
| `describe()`| `DataFrame.describe(percentiles=None, include=None, exclude=None)`                                 |
| `shape()`  | `DataFrame.shape`                                                                                 |
| `columns`  | `DataFrame.columns`                                                                               |
| `pivot_table()` | `DataFrame.pivot_table(values=None, index=None, columns=None, aggfunc='mean', ...)`             |

Note: The parameters in the syntax are often optional, and the default values are mentioned in the syntax. You can adjust them based on your specific use case.
```



In [ ]:
# Here's an example program for each of the functions with explanations:

#1. `dropna()`

import pandas as pd

# Create a DataFrame with missing values
data = {'Name': ['Alice', 'Bob', 'Charlie', None],
        'Age': [25, 30, None, 22],
        'Salary': [50000, 60000, 75000, None]}
df = pd.DataFrame(data)

# Drop rows with missing values
df.dropna(inplace=True)

print("DataFrame after dropping rows with missing values:")
print(df)

# Explanation: This program creates a DataFrame with missing values and uses the `dropna()` function to remove rows containing
# any missing values.

DataFrame after dropping rows with missing values:
    Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob  30.0  60000.0


In [ ]:
#2. `fillna()`

import pandas as pd

# Create a DataFrame with missing values
data = {'Name': ['Alice', 'Bob', 'Charlie', None],
        'Age': [25, 30, None, 22],
        'Salary': [50000, 60000, 75000, None]}
df = pd.DataFrame(data)

# Fill missing values in the 'Age' column with the mean
df['Age'].fillna(df['Age'].mean(), inplace=True)

print("DataFrame after filling missing values:")
print(df)
print(df.dropna())
# Explanation: This program fills missing values in the 'Age' column with the mean value of that column using the `fillna()` function.


DataFrame after filling missing values:
      Name        Age   Salary
0    Alice  25.000000  50000.0
1      Bob  30.000000  60000.0
2  Charlie  25.666667  75000.0
3     None  22.000000      NaN
      Name        Age   Salary
0    Alice  25.000000  50000.0
1      Bob  30.000000  60000.0
2  Charlie  25.666667  75000.0


In [ ]:
#3. `replace()`
import pandas as pd
# Create a DataFrame with a column containing specific values
data = {'Category': ['A', 'B', 'A', 'C', 'B']}
df = pd.DataFrame(data)

# Replace 'A' with 'New' in the 'Category' column
df['Category'].replace('A', 'New', inplace=True)
# replacing more than one value
replace_dict={'A':'AAA','B':'BBB','C':'CCC'}
df['Category'].replace(replace_dict, inplace=True)

print("DataFrame after replacing values:")
print(df)

# Explanation: This program replaces occurrences of 'A' with 'New' in the 'Category' column using the `replace()` function.


DataFrame after replacing values:
  Category
0      New
1      BBB
2      New
3      CCC
4      BBB


In [ ]:
#4. `loc()`

import pandas as pd

# Create a DataFrame with labeled rows and columns
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 22],
        'Salary': [50000, 60000, 75000]}
df = pd.DataFrame(data, index=['A', 'B', 'C'])
print(df)
# Select the row with index 'B' and the 'Age' and 'Salary' columns

selected_dat = df.loc['B', ['Age', 'Salary']]
selected_data = df.loc[['B','C'], ['Age', 'Salary']]

print("Selected data using loc:")
print(selected_dat)
print(selected_data)
# Explanation: This program uses the `loc()` function to select specific rows and columns from a DataFrame based on labels.


      Name  Age  Salary
A    Alice   25   50000
B      Bob   30   60000
C  Charlie   22   75000
Selected data using loc:
Age          30
Salary    60000
Name: B, dtype: object
   Age  Salary
B   30   60000
C   22   75000


In [ ]:
### 5. `iloc()`
import pandas as pd
# Create a DataFrame with labeled rows and columns
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 22],
        'Salary': [50000, 60000, 75000]}
df = pd.DataFrame(data, index=['A', 'B', 'C'])
# Select the first row and the first two columns using integer positions
selected_data = df.iloc[0, :2]
print("Selected data using iloc:")
print(selected_data)

# Explanation: This program uses the `iloc()` function to select specific rows and columns from a DataFrame based on integer positions.


Selected data using iloc:
Name    Alice
Age        25
Name: A, dtype: object


In [ ]:
# 6. `merge()`

import pandas as pd
# Create two DataFrames
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Salary': [50000, 60000, 70000]})
# Merge DataFrames based on the 'ID' column
merged_df = pd.merge(df1, df2, on='ID', how='inner')
print("Merged DataFrame:")
print(merged_df)
# Explanation: This program uses the `merge()` function to combine two DataFrames based on a common column ('ID' in this case).


Merged DataFrame:
   ID   Name  Salary
0   1  Alice   50000
1   2    Bob   60000


In [ ]:
# 7. concat()

import pandas as pd
# Create two DataFrames
df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
df2 = pd.DataFrame({'Name': ['Charlie', 'David'], 'Age': [22, 28]})
# Concatenate DataFrames along rows (axis=0)
concatenated_df = pd.concat([df1, df2], axis=0)
print("Concatenated DataFrame:")
print(concatenated_df)
# Explanation: This program uses the concat() function to concatenate two DataFrames along rows.

Concatenated DataFrame:
      Name  Age
0    Alice   25
1      Bob   30
0  Charlie   22
1    David   28


In [ ]:
# 8. `mean()`

import pandas as pd
# Create a DataFrame with numeric values
data = {'Value1': [10, 20, 30, 40],
        'Value2': [5, 15, 25, 35]}
df = pd.DataFrame(data)

# Calculate the mean of each column
column_means = df.mean()

print("Mean values for each column:")
print(column_means)
# Explanation: This program uses the `mean()` function to calculate the mean values of numeric columns in a DataFrame.


Mean values for each column:
Value1    25.0
Value2    20.0
dtype: float64


In [ ]:
### 9. `sum()`

import pandas as pd
# Create a DataFrame with numeric values
data = {'Value1': [10, 20, 30, 40],
        'Value2': [5, 15, 25, 35]}
df = pd.DataFrame(data)
# Calculate the sum of each column
column_sums = df.sum()
print("Sum values for each column:")
print(column_sums)
# Explanation: This program uses the `sum()` function to calculate the sum of numeric columns in a DataFrame.


Sum values for each column:
Value1    100
Value2     80
dtype: int64


In [ ]:
## 10. `groupby()`
import pandas as pd
# Create a DataFrame with categorical values
data = {'Category': ['A', 'B', 'A', 'B', 'A'],
        'Value': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)
# Group by the 'Category' column and calculate the mean of each group
grouped_df = df.groupby('Category').mean()
print("Grouped DataFrame with mean values:")
print(grouped_df)
# Explanation: This program uses the `groupby()` function to group a DataFrame by a specific column ('Category' in this case) and calculate the mean value for each group.


Grouped DataFrame with mean values:
          Value
Category       
A          30.0
B          30.0


In [ ]:
# # 11. read_csv()
# import pandas as p
# # Read a CSV file into a DataFrame
# # Example CSV file: 'example.csv'
# # df = pd.read_csv('example.csv')
# print("DataFrame after reading from CSV:")
# print(df)
# # Explanation: This program uses the read_csv() function to read data from a CSV file and create a DataFrame.

In [ ]:
# 12. head()
import pandas as pd
# Create a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 22, 28],
        'Salary': [50000, 60000, 75000, 70000]}
df = pd.DataFrame(data)
# Display the first 2 rows of the DataFrame
print("First 2 rows of the DataFrame:")
print(df.head(2))

First 2 rows of the DataFrame:
    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000


In [ ]:
# 13. tail()
import pandas as pd
# Create a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 22, 28],
        'Salary': [50000, 60000, 75000, 70000]}
df = pd.DataFrame(data)
# Display the last 3 rows of the DataFrame
print("Last 3 rows of the DataFrame:")
print(df.tail(3))
# Explanation: This program uses the tail() function to display the last 3 rows of a DataFrame.


Last 3 rows of the DataFrame:
      Name  Age  Salary
1      Bob   30   60000
2  Charlie   22   75000
3    David   28   70000


In [ ]:
# 14. info()
import pandas as pd
# Create a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 22],
        'Salary': [50000, 60000, 75000]}
df = pd.DataFrame(data)
# Display information about the DataFrame
df.info()
# Explanation: This program uses the info() function to display concise information about the DataFrame, including data types and missing values.


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   Salary  3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [ ]:
# 15. describe()
import pandas as pd
# Create a DataFrame with numeric values
data = {'Value1': [10, 20, 30, 40],
        'Value2': [5, 15, 25, 35]}
df = pd.DataFrame(data)
# Display summary statistics of the DataFrame
print("Summary statistics of the DataFrame:")
print(df.describe())
# Explanation: This program uses the describe() function to display summary statistics of numeric columns in a DataFrame.

Summary statistics of the DataFrame:
          Value1     Value2
count   4.000000   4.000000
mean   25.000000  20.000000
std    12.909944  12.909944
min    10.000000   5.000000
25%    17.500000  12.500000
50%    25.000000  20.000000
75%    32.500000  27.500000
max    40.000000  35.000000


In [ ]:
# 16. shape
import pandas as pd
# Create a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 22],
        'Salary': [50000, 60000, 75000]}
df = pd.DataFrame(data)
# Display the dimensions of the DataFrame
print("Dimensions of the DataFrame:")
print(df.shape)
# Explanation: This program uses the shape attribute to display the dimensions (number of rows and columns) of a DataFrame.

Dimensions of the DataFrame:
(3, 3)


In [ ]:
# 17. columns
import pandas as pd
# Create a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 22],
        'Salary': [50000, 60000, 75000]}
df = pd.DataFrame(data)
# Display the column labels of the DataFrame
print("Column labels of the DataFrame:")
print(df.columns)
# Explanation: This program uses the columns attribute to display the column labels of a DataFrame.

Column labels of the DataFrame:
Index(['Name', 'Age', 'Salary'], dtype='object')


In [ ]:
# 18. pivot_table()
import pandas as pd
# Create a DataFrame with values for a pivot table
data = {'Category': ['A', 'B', 'A', 'B'],
        'Year': [2021, 2020, 2021, 2021],
        'Value': [10, 20, 30, 40]}
df = pd.DataFrame(data)
# Create a pivot table with average values for each combination of 'Category' and 'Year'
pivot_table_df = df.pivot_table(values='Value', index='Category', columns='Year', aggfunc='sum')
print("Pivot table with average values:")
print(pivot_table_df)
# Explanation: This program uses the pivot_table() function to create a spreadsheet-style pivot table with average values
#  for each combination of 'Category' and 'Year'.

Pivot table with average values:
Year      2020  2021
Category            
A          NaN  40.0
B         20.0  40.0


In [ ]:
imdb_df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'runtime', 'spoken_languages', 'status', 'tagline',
       'title', 'Keywords', 'cast', 'crew', 'revenue', 'hrt', 'movie_profit'],
      dtype='object')

In [ ]:
# Try out here!!

high_rev = imdb_df.sort_values('revenue', ascending = False).head(5)
low_bud = imdb_df.sort_values('budget',ascending = True).head(5)
print("Movies with highest revenue\n",high_rev[['title','popularity','runtime']])
print("\nMovies with lowest budget\n",low_bud[['title','popularity','runtime']])
print("Highest revenue popularity:",high_rev[['title','popularity','runtime']])
print("Lowest budget popularity:",low_bud['popularity'])

Movies with highest revenue
                                title  popularity  runtime
1126                    The Avengers   89.887648    143.0
1761                       Furious 7   27.275687    137.0
2770         Avengers: Age of Ultron   37.379420    141.0
684             Beauty and the Beast  287.253654    129.0
2322  Transformers: Dark of the Moon    4.503505    154.0

Movies with lowest budget
                            title  popularity  runtime
895               Gray Lady Down    3.507084    111.0
594                    Tommy Boy   11.971318     97.0
595   A Prince (almost) Charming    1.985348     88.0
1252         Murder in the First    9.518564    122.0
2144               The Final Cut    1.797462     96.0
Highest revenue popularity:                                title  popularity  runtime
1126                    The Avengers   89.887648    143.0
1761                       Furious 7   27.275687    137.0
2770         Avengers: Age of Ultron   37.379420    141.0
684        

In [ ]:
# Suppose we want to convert the column network to uppercase
def upper_case(column):
    return column.upper()
capitalized_title=imdb_df['title'].apply(upper_case)
capitalized_title.head()

0                      HOT TUB TIME MACHINE 2
1    THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT
2                                    WHIPLASH
3                                     KAHAANI
4                                  MARINE BOY
Name: title, dtype: object

In [ ]:
# defines a function called revised_profit that takes two arguments,
# revenue and budget, and returns a new profit value if the revenue is greater than 0, or NaN if the revenue is less than or equal to 0
def revised_profit(revenue,budget):
    if revenue > 0:
        new_profit = revenue - budget
    else:
        new_profit = np.nan
    return new_profit

imdb_df['new_profit'] = imdb_df.apply(lambda x: revised_profit(x['revenue'],x['budget']),axis=1)
imdb_df['new_profit'].head()

#

0    -1685349
1    55149435
2     9792000
3    14800000
4     3923970
Name: new_profit, dtype: int64



```
lambda x: revised_profit(x['revenue'], x['budget']): This is a lambda function
 (an anonymous function) that takes a row x from the DataFrame and applies the
  function revised_profit to the 'revenue' and 'budget' columns of that row.

axis=1: Indicates that the lambda function should be applied to each row of the DataFrame.
By default the axis value will be axis=0 in such case and apply column-wise. as
we want to perform operation on row-wise we have to change the axis value
according to it.

```



we can merge or combine data from different sources that share a common column or attribute.

We can merge dataframes using the following methods

pd.concat( [df] , axis)

pd.merge( df1, df2 ,on,how,suffixes)

In [ ]:
# we can merge or combine data from different sources that share a common column or attribute.


In [ ]:
# 📽️👨‍🎬👩‍🎬 Every movie director has been asked to add 10 minutes to their movies to promote 🚭 no smoking,
# 👧📚 child education, climate change 🌍 and other social issues. Your task is to update the runtime of each movie by adding 10 minutes
# and creating a new column called "new_runtime". Can you write the code to accomplish this in pandas? 💻🐼

print(imdb_df.columns)
imdb_df['new_runtime']=imdb_df['runtime']+10
print(imdb_df['new_runtime'].head())
# print(imdb_df['runtime'].head())

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'runtime', 'spoken_languages', 'status', 'tagline',
       'title', 'Keywords', 'cast', 'crew', 'revenue', 'hrt', 'movie_profit',
       'new_profit'],
      dtype='object')
0    103.0
1    123.0
2    115.0
3    132.0
4    128.0
Name: new_runtime, dtype: float64


### **Customer Information:**

You have a dataset which contains customer information of 8 customers. Your task is to perform the following the actions based on the data:

1. Identify missing values: In the dataset, the Age column for customer ID 1007 and the Phone column for customer ID 1006 are missing values.

2. Fill in missing values: For the Age column of customer ID 1007, the mean value of the Age column can be used as a reasonable approximation, which is 32. For the Phone column of customer ID 1006, we can either delete the row or try to obtain the missing phone number by contacting the customer.

3. Inconsistent formats: The Phone column has inconsistent formats - some are formatted with dashes and others are formatted with parentheses or periods. To standardize the format, we can remove all non-numeric characters and keep only the digits.

4. Standardize data types: The Phone column should be stored as a string instead of a numeric value to preserve the formatting. The Age column can be stored as an integer.

5. Identify and handle outliers or inconsistencies: In this dataset, there are no obvious outliers or inconsistencies. However, depending on the specific requirements of the project or analysis, there may be other issues that need to be addressed.

In [ ]:
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')
path='/content/drive/MyDrive/Colab Notebooks/customer_information.csv'
customer_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/customer_information.csv')
customer_data.columns

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Index(['Customer ID', 'Name', 'Age', 'Email', 'Phone', 'Gender'], dtype='object')

In [ ]:
customer_data.columns
customer_data['Age'].fillna(customer_data['Age'].mean(),inplace=True)
index_to_delete=customer_data[customer_data['Customer ID'] == 1006].index
customer_data.drop(index_to_delete,inplace=True)
customer_data['Phone'].replace('[\D]','',regex=True)

0    5551234567
1    5555555555
2    5551234567
3    5555555555
4    5555551234
6    5555555555
7    5555555555
Name: Phone, dtype: object

### **Inspecting Movie Data:**

Suppose you are a data analyst working for a movie studio. Your boss has asked you to analyze a dataset containing information about movies, including the movie title, release year, director, genre, and box office revenue. Your boss wants to know:

1. What is the average box office revenue per year for the movies in the dataset?
2. Which genres are the most popular and how many movies have been released in each genre?
3. Who are the top 5 directors in terms of box office revenue?
4. Use Pandas to analyze the dataset and provide a report summarizing your findings. Be sure to include any data cleaning or transformation steps you took to arrive at your conclusions.

# notes
This line adds a new column 'release_year' to the DataFrame (imdb_df) by converting the 'release_date_column' to a datetime format and extracting the year component. The to_datetime function is used to convert the release date to a datetime object, and imdb_df.year extracts the year.

In [ ]:
# 1.
imdb_df.head(3)
imdb_df['release_date']=pd.to_datetime(imdb_df['release_date'])
imdb_df['release_date']
imdb_df['release_year']=imdb_df['release_date'].dt.year
imdb_df['release_year']
average_revenue_year=imdb_df.groupby('release_year')['revenue'].mean()
average_revenue_year

In [ ]:
# 2.Which genres are the most popular and how many movies have been released in each genre?
import pandas as pd


# Use explode to separate each genre into individual rows
df_exploded = imdb_df['genres'].explode().reset_index(drop=True)

# Display the result
print(df_exploded)
# Count the occurrences of each genre
genre_counts = df_exploded[['name']].value_counts()

# Display the result
print(genre_counts)


In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/Colab Notebooks/movies.csv'
movies = pd.read_csv(path)
movies

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Title  Release Year  \
0                                       Star Wars          1977   
1                                            Jaws          1975   
2   Indiana Jones and the Raiders of the Lost Ark          1981   
3                                    Ghostbusters          1984   
4                              Back to the Future          1985   
5                                   The Godfather          1972   
6                                   The Lion King          1994   
7                                    Forrest Gump          1994   
8                                 The Dark Knight          2008   
9                                          Avatar          2009   
10                                   The Avengers          2012   
11                               The Hunger Games          2012   
12                             Mad Max: Fury Road          2015   
13                                   Wonder Woman          2017   
14                                  Black Panther          2018   
15                                          Joker          2019   

                        Director      Genre  Box Office  
0                   George Lucas     Sci-Fi       775.4  
1               Steven Spielberg     Horror       470.7  
2               Steven Spielberg     Action       389.9  
3                   Ivan Reitman     Comedy       295.2  
4                Robert Zemeckis     Sci-Fi       381.1  
5           Francis Ford Coppola      Drama       245.0  
6   Roger Allers and Rob Minkoff  Adventure       987.5  
7                Robert Zemeckis      Drama       677.4  
8              Christopher Nolan     Action      1005.0  
9                  James Cameron     Sci-Fi      2787.8  
10                   Joss Whedon     Action      1518.8  
11                     Gary Ross     Action       694.4  
12                 George Miller     Action       378.9  
13                 Patty Jenkins     Action       821.8  
14                  Ryan Coogler     Action      1346.9  
15                 Todd Phillips      Drama      1074.3

In [ ]:
movies.columns
# 1.convert to date_tiome , extract year, calculate mean or average by gruoping by year
# this will be done if the values will not be not in correct form.
average_revenue_year=movies.groupby('Release Year')['Box Office'].mean()
average_revenue_year
# 2.Which genres are the most popular and how many movies have been released in each genre?
# .value_counts(): This function is applied to the 'Genre' column,
#  and it returns a series with the counts of unique values in that column.
movies_per_genre=movies['Genre'].value_counts()
movies_per_genre
#3. Who are the top 5 directors in terms of box office revenue?
# groupby directors,sumof boxoffice collection, sort in desc,print top 5
directors_revenue=movies.groupby('Director')['Box Office'].sum()
sorted_directors=directors_revenue.sort_values(ascending=False)
sorted_directors.head()


Director
James Cameron      2787.8
Joss Whedon        1518.8
Ryan Coogler       1346.9
Todd Phillips      1074.3
Robert Zemeckis    1058.5
Name: Box Office, dtype: float64

In [ ]:
# 4.Use Pandas to analyze the dataset and provide a report summarizing your findings.
# Be sure to include any data cleaning or transformation steps you took to arrive at your conclusions.

# import numpy, pandas and drive
import numpy as np
import pandas as pd
from google.colab import drive
# mounting the drive into colab
drive.mount('/content/drive')
# set file path
path = '/content/drive/MyDrive/Colab Notebooks/movies.csv'
# read file and store in a dataframe
movies = pd.read_csv(path)
movies
# 1.What is the average box office revenue per year for the movies in the dataset?
average_revenue_year=movies.groupby('Release Year')['Box Office'].mean()
# 2.Which genres are the most popular and how many movies have been released in each genre?
movies_per_genre=movies['Genre'].value_counts()
# 3.Who are the top 5 directors in terms of box office revenue?
directors_revenue=movies.groupby('Director')['Box Office'].sum()
sorted_directors=directors_revenue.sort_values(ascending=False)
print("Average revenue per year:",average_revenue_year)
print("Movies in each geres:",movies_per_genre)
print("Top 5 directors based on their box office collection:\n",sorted_directors.head())