<a href="https://colab.research.google.com/github/manishaachary13/Alma_study/blob/main/module_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_array = []
my_array = [1, 2, 3, 4, 5]
import array
my_array = array.array('i', [1, 2, 3, 4, 5])
print(my_array)
import numpy as np
np_array = np.array([[1, 2, 3], [4, 5, 6]])
np_array

array('i', [1, 2, 3, 4, 5])


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# buf_info=my_array.data
# print(buf_info)
# fill method is used to fill array wih specific value
# array module does not have fill method while numpy has
np_array.fill(-1)
print(np_array)

[[-1 -1 -1]
 [-1 -1 -1]]


In [ ]:
arr = array.array('i', [1, 2, 3, 4, 5])
# numpy does not has buffer_info
buffer_info = arr.buffer_info()
print(buffer_info)
# Output: (139652048, 5)


(136577639090288, 5)


In [ ]:
# What is the output of the following code?

import array
arr = array.array('i', [1, 2, 3])
arr.append(4)
print(arr)

array('i', [1, 2, 3, 4])


In [ ]:
import numpy as np

my_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])  # a two-dimensional array of integers



To traverse or iterate over an array, you can use a loop to access each element in the array one at a time. For example, you can use a for loop to print each element in an array

In [ ]:
import numpy as np
my_array=[1,2,3,4,5,7]
for num in my_array:
    print(num)
if 40 in my_array:
    print("true")
else:
    print(False)

1
2
3
4
5
7
False


To search for a specific element in an array, you can use a loop to check each element in the array one at a time. For example, you can use a for loop and an if statement to find the index of the first occurrence of a specific element in an array:

In [ ]:
search_num=6
for index,num in enumerate(my_array):
    if num==search_num:
        print(f"{num} find in index {index}")
        break
else:
    print("number connot found.")

number connot found.


Numpy arrays are not designed for dynamic resizing like Python lists, but you can still append new items by creating a new array with the additional elements. Here's how you can append new items to a numpy array.

In [ ]:
appended_array=np.append(my_array,[6])
print(appended_array)
concat_array=np.concatenate((appended_array,[9]))
print(concat_array)

[1 2 3 4 5 7 6]
[1 2 3 4 5 7 6 9]


In [ ]:
value_to_del=4
my_array=np.array([1,2,3,4,5,6,7,8])
print(my_array)
mask=my_array != value_to_del
new_array=my_array[mask]
print(mask)
print(new_array)

[1 2 3 4 5 6 7 8]
[ True  True  True False  True  True  True  True]
[1 2 3 5 6 7 8]


In [ ]:
print(my_array)
var=4
mask=my_array != var
new_array=my_array[mask]
print(new_array)
type(new_array)
type(new_array[0])

[1 2 3 4 5 6 7 8]
[1 2 3 5 6 7 8]


numpy.int64

In [ ]:
index_to_del=4
print(my_array)
new_array=np.delete(my_array,index_to_del)
print(new_array)
my_array = my_array[my_array != 21]
print(my_array)

[64 58 25 75  5 21]
[64 58 25 75 21]
[64 58 25 75  5]


In [ ]:
import numpy as np
num_array=np.array([21,5,75,8,25,58,64])
# num_array.sort()
# print(num_array)
# num_array[::-1].sort()
# print(num_array)
char_array=np.array(['c','t','e','y','w'])
print(char_array)
char_array.sort()
print(char_array)
sorted_arr=np.sort(num_array)
print(sorted_arr)
my_array = np.flip(num_array)
print(my_array)

['c' 't' 'e' 'y' 'w']
['c' 'e' 't' 'w' 'y']
[ 5  8 21 25 58 64 75]
[64 58 25  8 75  5 21]


In [ ]:
# Flatten a 2D array
arr_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened = [num for sublist in arr_2d for num in sublist]

# Print the flattened array
print("Flattened array:", flattened)

Flattened array: [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# Find the index of the maximum value in the array
max_val = max(arr)
max_index = arr.index(max_val)

# Print the index of the maximum value
print("Index of maximum value:", max_index)

Longest palindrome

In [ ]:
string = input("Enter a string: ")
longest_palindrome = ""

for i in range(len(string)):
    for j in range(i, len(string)):
        substring = string[i:j+1]
        if substring == substring[::-1] and len(substring) > len(longest_palindrome):
            longest_palindrome = substring


print("Longest palindrome substring:", longest_palindrome)

Write a Python program that takes a string as input and returns the most common character in the string.

In [ ]:
%%time
strin = input("Enter a string: ")
dic={}
for ch in strin:
    if ch not in dic:
        dic[ch]=1
    else:
        dic[ch]+=1
print(max(dic, key=dic.get))

Enter a string: manisha
2
CPU times: user 2.41 s, sys: 400 ms, total: 2.81 s
Wall time: 2min 37s


Write a Python program that takes an array of integers as input and removes all duplicate values from the array.

In [ ]:
array = [3, 8, 1, 6, 2, 10, 4, 7, 5, 9, 1, 2, 5, 8]
unique_array = []

for num in array:
    if num not in unique_array:
        unique_array.append(num)

print("Array with duplicates removed:", unique_array)

Array with duplicates removed: [3, 8, 1, 6, 2, 10, 4, 7, 5, 9]


Write a Python program that takes two strings as input and checks if they are anagrams of each other.

In [ ]:
string1 = input("Enter string 1: ")
string2 = input("Enter string 2: ")

if sorted(string1) == sorted(string2):
    print("The strings are anagrams of each other.")
else:
    print("The strings are not anagrams of each other.")

Enter string 1: listen
Enter string 2: silent
The strings are anagrams of each other.


The time complexity of this code is O(nlogn), where n is the length of the longest string. This is because the sorted function has a time complexity of O(nlogn) for sorting a list of length n.

The space complexity is also O(n), where n is the length of the longest string. This is because the sorted function creates a new list with the same length as the input string, so the space required is proportional to the length of the longest string.

Write a program to remove duplicate elements from an array.

In [ ]:
import array

arr = array.array('i', [1, 2, 2, 3, 4, 4, 5])
unique_arr = list(set(arr))
print("Array with duplicates:", arr)
print("Array without duplicates:", unique_arr)


Array with duplicates: array('i', [1, 2, 2, 3, 4, 4, 5])
Array without duplicates: [1, 2, 3, 4, 5]


Write a program to rotate the elements of an array to the left by a specified number of positions.

In [ ]:
import array

def rotate_left(arr, positions):
    return arr[positions:] + arr[:positions]

arr = array.array('i', [1, 2, 3, 4, 5])
rotated_arr = rotate_left(arr, 2)
print("Rotated array:", rotated_arr)


Rotated array: array('i', [3, 4, 5, 1, 2])


Write a program to find the second-largest element in an array.

In [ ]:
import array

arr = array.array('i', [10, 5, 15, 20, 25])
sorted_arr = sorted(set(arr), reverse=True)
second_largest = sorted_arr[1] if len(sorted_arr) > 1 else None
print("Second-largest element:", second_largest)


Second-largest element: 20


To convert a list, set, or any iterable sequence into an array in Python, you can use the `array` module. The `array` module provides the `array` function, which takes a typecode and an iterable as arguments.

Here's an example of how to convert a list to an array:

```python
import array

my_list = [1, 2, 3, 4, 5]
arr_from_list = array.array('i', my_list)

print(arr_from_list)
# Output: array('i', [1, 2, 3, 4, 5])
```

In this example, `arr_from_list` is an array of signed integers (`'i'` typecode) created from the elements of the `my_list` list.

You can follow the same approach for sets or other iterable sequences:

```python
import array

my_set = {1, 2, 3, 4, 5}
arr_from_set = array.array('i', my_set)

print(arr_from_set)
# Output: array('i', [1, 2, 3, 4, 5])
```

The key is to use the `array` function and specify the appropriate typecode for the elements in your sequence.

Here are some commonly used typecodes:

- `'i'`: Signed integer
- `'f'`: Float
- `'d'`: Double

Make sure to choose the typecode that best matches the type of elements in your sequence.

In [ ]:
import array

my_string = "hello"
arr_from_string = array.array('b', [ord(char) for char in my_string])   #ord() returns unicode of value

array('b', [104, 101, 108, 108, 111])

In [ ]:
string = "Hello World"
substring = string[6:]
print(substring)  # Output: "World"

string = "apple, banana, orange"
substring = string.split(", ")[2]
print(substring)  # Output: "banana"


World
orange


In [ ]:
'''Certainly! The operation you're referring to is string slicing, and it involves extracting a portion (substring) from a given string in Python. Additionally, methods like `split()`, `partition()`, and `find()` can also be used for substring extraction. Let's delve into each method with detailed notes and examples:

## String Slicing:

String slicing is a technique to extract a portion of a string by specifying the start and end indices. The syntax is `string[start:end]`, where the substring includes characters from the `start` index up to, but not including, the `end` index.

python'''
original_string = "Python is powerful"

# Extracting a substring using string slicing
substring = original_string[7:10]
print(substring)  # Output: 'is '

'''
You can omit either the `start` or `end` index to slice from the beginning or up to the end, respectively.

'''
# Slicing from the beginning
substring_beginning = original_string[:6]
print(substring_beginning)  # Output: 'Python'

# Slicing up to the end
substring_end = original_string[13:]
print(substring_end)  # Output: 'powerful'
'''

Negative indices can be used for slicing from the end of the string.

'''
# Slicing from the end
substring_from_end = original_string[-8:-1]
print(substring_from_end)  # Output: 'powerful'

## String Methods:

### 1. split():

# The `split()` method splits a string into a list of substrings based on a specified delimiter. If no delimiter is provided, it splits on whitespace.


sentence = "Python is versatile and powerful"

# Splitting the string into words
words = sentence.split()
print(words)  # Output: ['Python', 'is', 'versatile', 'and', 'powerful']

# You can also split based on a custom delimiter.


date = "2022-11-04"

# Splitting the string using '-'
date_parts = date.split('-')
print(date_parts)  # Output: ['2022', '11', '04']


### 2. partition():

# The `partition()` method splits a string into three parts based on the first occurrence of a specified separator. It returns a tuple containing the substring before the separator, the separator itself, and the substring after the separator.

# ``python
sentence = "Python is easy to learn"

# Partitioning the string using 'is'
result = sentence.partition('easy')
print(result)  # Output: ('Python ', 'is', ' easy to learn')
# ```

### 3. find():

# The `find()` method searches for a substring within the given string and returns the index of the first occurrence. If the substring is not found, it returns -1.

# ```python
sentence = "Python is fun"

# Finding the index of 'is'
index = sentence.find('is')
print(index)  # Output: 7

# Finding the index of 'Java' (not present)
index_not_found = sentence.find('Java')
print(index_not_found)  # Output: -1
# ```

# These methods provide different ways to extract substrings from strings in Python. Depending on the specific use case, you can choose the most suitable method for your needs.

is 
Python
erful
powerfu
['Python', 'is', 'versatile', 'and', 'powerful']
['2022', '11', '04']
('Python is ', 'easy', ' to learn')
7
-1


In [ ]:
import re

# Using regex to remove all spaces
sample_string = "This is a regex example."
no_spaces = re.sub(r'\s', '', sample_string)
print(no_spaces)  # This will print the string without any spaces

Thisisaregexexample.


In [ ]:
# Timing a built-in method
import time

sample_string = " " * 1000000  # A string with a million spaces
start_time = time.time()
sample_string.replace(" ", "")
end_time = time.time()

print(f"Built-in replace method took {end_time - start_time} seconds.")

Built-in replace method took 0.003125429153442383 seconds.


In [ ]:
import sys

sample_string = " " * 1000000
print(f"Memory usage of original string: {sys.getsizeof(sample_string)} bytes")

Memory usage of original string: 1000049 bytes


1. **Naive String Matching**: This is a simple algorithm that involves comparing the pattern with each possible substring of the text.

In [ ]:
def naive_string_matching(text, pattern):
    '''check if pattern is in string if yes
Then in which which index position.and this is docstring
You can print only docstring by printing function name with? Mark without braces.'''
    # Get the lengths of the text and pattern strings
    n = len(text)
    m = len(pattern)

    # Initialize an empty list to store the starting indices of pattern matches
    matches = []

    # Loop through each possible starting index for the pattern in the text
    for i in range(n - m + 1):
        # Initialize a counter j to 0 and compare the characters of the pattern to the corresponding characters in the text
        j = 0
        while j < m and pattern[j] == text[i+j]:
            j += 1
        # If all characters match, add the starting index to the matches list
        if j == m:
            matches.append(i)

    # Return the list of starting indices of pattern matches
    return matches

# Example usage
text = "ABCDABCDEFABC"
pattern = "ABC"
matches = naive_string_matching(text, pattern)
naive_string_matching?
print("Pattern matches found at indices:", matches)

Pattern matches found at indices: [0, 4, 10]


🔍🔍🔍

 Scenario: A company has a list of employee names and their employee IDs. The company needs to generate email addresses for each employee using the following format: firstname.lastname@company.com. However, some employees have multiple first or last names, separated by spaces, and their employee IDs have leading zeros that need to be removed. Write a Python program to generate email addresses for each employee.

In [ ]:
# Employee information
names = ["John Smith", "Jane Doe", "James William Johnson"]
ids = ["001234", "000987", "005678"]

def generate_email(employee_name, employee_id):
    # Split the full name into first and last names
    name_parts= employee_name.split()
    first_name=name_parts[0]
    last_name=name_parts[-1]
    if len(name_parts)>2:
        first_name="".join(name_parts[:-1])
        last_name=name_parts[-1]
    # print(first_name)
    # print(last_name)

    # Remove leading zeros from the employee ID
    # cleaned_id = str(int(employee_id))
    # there is another way is using lstrip()
    cleaned_id = employee_id.lstrip("0")

    # Generate the email address using the specified format
    email = f"{first_name.lower()}.{last_name.lower()}@company.com"

    return email,cleaned_id

# Generate and print email addresses for each employee
for name, employee_id in zip(names, ids):
    email_address, id = generate_email(name, employee_id)
    print(f"{name}'s email address: {email_address} and id:{id}")


John
Smith
John Smith's email address: john.smith@company.com and id:1234
Jane
Doe
Jane Doe's email address: jane.doe@company.com and id:987
JamesWilliam
Johnson
James William Johnson's email address: jameswilliam.johnson@company.com and id:5678


🧑🧑🧑
You are a teacher who needs to grade a stack of math homework assignments. You want to make sure that the students have followed the instructions and written their answers in the correct format. The correct format for the answer is a number followed by the unit of measurement, separated by a space. For example, "10 meters" or "5 seconds".

You decide to use naive string matching to find all the answers that are not in the correct format so that you can provide feedback to the students.

Can you write a Python code to help you find the answers that are not in the correct format?

In [ ]:
def find_incorrect_format(answers):
    incorrect_format = []

    for i, answer in enumerate(answers, 1):
        # Split the answer into parts based on spaces
        parts = answer.split()

        # Check if the answer has the correct format (a number followed by a unit)
        if len(parts) != 2 or (not parts[0].replace('.', '').isdigit() and not parts[0].replace('-', '').isdigit()):
            incorrect_format.append((i, answer))

    return incorrect_format

# Example usage
homework_answers = ["10 meters","5 seconds","2.89 meter second","15","2 minutes","7 apples"]

incorrect_answers = find_incorrect_format(homework_answers)

if incorrect_answers:
    print("Answers with incorrect format:")
    for index, answer in incorrect_answers:
        print(f"  - Answer {index}: {answer}")
else:
    print("All answers are in the correct format.")


Answers with incorrect format:
  - Answer 3: 2.89 meter second
  - Answer 4: 15


In [ ]:
# Step 1: Define two string variables
favorite_emoji = "🚀"
your_name = "John"

# Step 2: Concatenate the two strings
concatenated_string = favorite_emoji + your_name

# Step 3: Convert the concatenated string to uppercase
uppercase_string = concatenated_string.upper()

# Step 4: Replace the emoji with a new emoji
new_emoji = "🌟"
modified_string = concatenated_string.replace(favorite_emoji, new_emoji)

# Step 5: Find the position of the letter "h"
position_of_h = concatenated_string.find("h")

# Print the results
print("Favorite Emoji:", favorite_emoji)
print("Your Name:", your_name)
print("Concatenated String:", concatenated_string)
print("Uppercase String:", uppercase_string)
print("Modified String:", modified_string)
print("Position of 'h':", position_of_h)


Favorite Emoji: 🚀
Your Name: John
Concatenated String: 🚀John
Uppercase String: 🚀JOHN
Modified String: 🌟John
Position of 'h': 3


 Create a 2D Array and Slice Rows and Columns

In [ ]:
import numpy as np

# Create a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice rows from index 0 to 1 (exclusive)
sliced_rows = matrix[0:2, :]

# Slice columns from index 1 to the end
sliced_columns = matrix[:, 1:]

# Print the results
print("Original Matrix:")
print(matrix)
print("\nSliced Rows:")
print(sliced_rows)
print("\nSliced Columns:")
print(sliced_columns)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sliced Rows:
[[1 2 3]
 [4 5 6]]

Sliced Columns:
[[2 3]
 [5 6]
 [8 9]]


Explanation:

We created a 3x3 matrix using NumPy.
sliced_rows contains rows from index 0 to 1 (exclusive), resulting in the first two rows.
sliced_columns contains columns from index 1 to the end, resulting in the second and third columns.

Extract Diagonal Elements from a Matrix
python


In [ ]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract diagonal elements
diagonal_elements = np.diag(matrix)

# Print the diagonal elements
print("Diagonal Elements:")
print(diagonal_elements)


Diagonal Elements:
[1 5 9]


**Task Assignment:**
Develop a Python program that dynamically generates a matrix of random numbers. The program should be designed to accept a random number of rows and columns as input. Additionally, provide functionality to print and display the resulting matrix.

Please structure the code professionally and include comments for clarity. Consider utilizing functions to enhance modularity and readability.

In [ ]:

import random

def create_random_matrix(rows, cols):
    matrix = [[random.randint(1, 20) for i in range(cols)] for j in range(rows)]
    return matrix

# Example: create a 3x3 matrix
rows = random.randint(1,5)
cols = random.randint(1,5)
random_matrix = create_random_matrix(rows, cols)

# Print the matrix
for row in random_matrix:
    print(row)


[3, 7]
[15, 17]
[7, 2]
[9, 16]
[4, 5]


Explanation:

We created a 3x3 matrix.
np.diag(matrix) extracts the diagonal elements of the matrix.

Create a Random 2D Array and Perform Slicing
python


In [ ]:
import numpy as np

# Create a random 3x4 matrix
random_matrix = np.random.rand(3, 4)

# Slice a submatrix from the original matrix
submatrix = random_matrix[1:3, 0:2]

# Print the results
print("Random Matrix:")
print(random_matrix)
print("\nSubmatrix:")
print(submatrix)


Random Matrix:
[[0.42320534 0.19400811 0.88398434 0.95879156]
 [0.19028494 0.7945481  0.10314774 0.54153298]
 [0.90801529 0.04049576 0.99591124 0.87791685]]

Submatrix:
[[0.19028494 0.7945481 ]
 [0.90801529 0.04049576]]


In [ ]:
import numpy as np

# Set the range for random numbers
lower_limit = 1
upper_limit = 30

# Generate a 3x4 matrix of random integers between 1 and 30
random_matrix = np.random.randint(lower_limit, upper_limit + 1, size=(3, 4))

# Print the matrix
print(random_matrix)


[[ 8  2  3 30]
 [10 19  5 30]
 [13  3  3 18]]


Explanation:

We created a random 3x4 matrix using np.random.rand.
submatrix is a sliced portion of the original matrix, containing rows from index 1 to 2 and columns from index 0 to 1.

Matrix Multiplication

In [ ]:
import numpy as np

# Create two matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
result_matrix = np.dot(matrix_a, matrix_b)

# Print the result
print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nResult Matrix (Matrix Multiplication):")
print(result_matrix)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result Matrix (Matrix Multiplication):
[[ 58  64]
 [139 154]]


Explanation:

We created two matrices, A and B.
The np.dot(matrix_a, matrix_b) performs matrix multiplication.
The resulting matrix is the product of matrix A and matrix B.

Element-wise Addition and Subtraction

In [ ]:
import numpy as np

# Create two matrices
matrix_x = np.array([[1, 2], [3, 4]])
matrix_y = np.array([[5, 6], [7, 8]])

# Perform element-wise addition and subtraction
addition_result = matrix_x + matrix_y
subtraction_result = matrix_x - matrix_y

# Print the results
print("Matrix X:")
print(matrix_x)
print("\nMatrix Y:")
print(matrix_y)
print("\nElement-wise Addition Result:")
print(addition_result)
print("\nElement-wise Subtraction Result:")
print(subtraction_result)


Matrix X:
[[1 2]
 [3 4]]

Matrix Y:
[[5 6]
 [7 8]]

Element-wise Addition Result:
[[ 6  8]
 [10 12]]

Element-wise Subtraction Result:
[[-4 -4]
 [-4 -4]]


Explanation:

We created two matrices, X and Y.
matrix_x + matrix_y performs element-wise addition.
matrix_x - matrix_y performs element-wise subtraction.

Transpose of a Matrix

In [ ]:
import numpy as np

# Create a matrix
original_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Calculate the transpose of the matrix
transposed_matrix = original_matrix.T

# Print the results
print("Original Matrix:")
print(original_matrix)
print("\nTransposed Matrix:")
print(transposed_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]]

Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


Explanation:

We created a matrix, original_matrix.
.T is used to calculate the transpose of the matrix, swapping rows with columns.

Array Indexing and Boolean Indexing

In [ ]:
import numpy as np

# Create an array
num_array = np.array([1, 2, 3, 4, 5])

# Access elements using indexing
third_element = num_array[2]

# Boolean indexing to filter elements
filtered_elements = num_array[num_array > 2]

# Print the results
print("Original Array:")
print(num_array)
print("\nThird Element:")
print(third_element)
print("\nFiltered Elements (greater than 2):")
print(filtered_elements)


Original Array:
[1 2 3 4 5]

Third Element:
3

Filtered Elements (greater than 2):
[3 4 5]


Explanation:

We created a NumPy array, num_array.
num_array[2] accesses the third element (index 2) of the array.
num_array[num_array > 2] uses boolean indexing to filter elements greater than 2.

Factorial: Write a recursive function to compute the factorial of a given number. The factorial of n is defined as the product of all positive integers from 1 to n.

In [ ]:
def factorial(n):
    if n == 0:  # Base case: if n equals 0
        return 1  # Return 1 (as 0! equals 1)
    else:  # If n is not equal to 0
        # Recursively call the function with n-1 as the argument and multiply the result by n
        return n * factorial(n-1)
# input a number by user
number=int(input("Enter a number:"))
# if number is a negative than factorial can not be possible.
if number<0:
    print("Sorry! factorial is can not be calculated on -ve number.")
# Factorial of 1 is 1
elif number==1:
    print(f"Factorial of {number} is 1")
# call the factorial function and print it
else:
    print(f"Factorial of {number} is {factorial(number)}")

# Example usage
# print(factorial(5))  # Output: 120 (as 5! equals 120)


Enter a number:5
Factorial of 5 is 120
120


Fibonacci sequence: Write a recursive function to compute the nth number in the Fibonacci sequence. The Fibonacci sequence is a sequence of numbers where each number is the sum of the two preceding ones, starting from 0 and 1.

In [ ]:
def fibonacci(n):
    if n <= 1:  # Base case: if n is less than or equal to 1
        return n  # Return n (i.e., 0 if n is 0, 1 if n is 1)
    else:  # If n is greater than 1
        # Recursively call the function with n-1 and n-2 as the arguments and add the results
        return fibonacci(n-1) + fibonacci(n-2)

# Example usage
print(fibonacci(10))  # Output: 13 (as the 7th Fibonacci number is 13)

55


### **Write a program to find the sum of natural numbers up to n using recursion.**

In [ ]:
def sum_number(n):
    if n == 1:      #base-case
        return 1
    else:
        return n+sum_number(n-1)    #recursive call
number=int(input("Enter a number to find sum upto that number: "))
# not allowed -ve number
if number<0:
    print("Invalid number. Enter a positive number.")
else:
    print(f"Sum of natural number upto {number} is {sum_number(number)}")


Enter a number to find sum upto that number12
Sum of natural number upto 12 is 78


### **Write a program to print the Fibonacci series up to n terms using recursion.**

In [ ]:
def fibonacci(n):
    if n<=1:
        return n
    else:
        return fibonacci(n-1)+fibonacci(n-2)
num=int(input("Enter a number: "))
# Checking if the input is valid
if num <= 0:
    print("Invalid input. Please enter a positive integer.")
else:
    print("Fibonacci series:")
    for i in range(num):
        print(fibonacci(i))


Enter a number: 5
Fibonacci series:
0
1
1
2
3


### **Write a program to find the nth term in the Tribonacci sequence using recursion.**

In [ ]:
def tribonacci(n):
    if n == 0 or n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return tribonacci(n-1) + tribonacci(n-2) + tribonacci(n-3)

# Taking input from user
num = int(input("Enter a number: "))

# Checking if the input is valid
if num <= 0:
    print("Invalid input. Please enter a positive integer.")
else:
    print("tribonacci series:")
    for i in range(num):
        print(tribonacci(i))

Enter a number: 6
tribonacci series:
0
0
1
1
2
4


### **Write a program to find the sum of digits of a given number using recursion.**

In [ ]:
def sum_of_digits(n):
    if n == 0:
        return 0
    else:
        return n%10 + sum_of_digits(n//10)

# Taking input from user
num = int(input("Enter a number: "))

# Checking if the input is valid
if num < 0:
    print("Invalid input. Please enter a non-negative integer.")
else:
    print("The sum of digits of", num, "is", sum_of_digits(num))

Enter a number: 4
The sum of digits of 4 is 4


In [ ]:
# linear search
import array
def linear_search(arr,search_item):
    for i in range(len(arr)):
        if arr[i]==search_item:
            return i
    return -1
arr=array.array('i',[1,2,3,4,5,6,7])
search_item=6
result=linear_search(arr,search_item)
if result!=-1:
    print(f"{search_item} found in index {result}")
else:
    print("Not found")


6 found in index 5


In [ ]:
# recursive linear search
import array
def recursive_linear_search(arr,search_item,index):
    if index >= len(arr):
        return -1
    elif search_item == arr[index]:
        return index
    else:
        return recursive_linear_search(arr,search_item, index+1)

arr=array.array('i',[1,2,3,4,5,7])
search_item=2
result=recursive_linear_search(arr,search_item,0)
if result!=-1:
    print(f"{search_item} found in index {result}")
else:
    print("Not found")



2 found in index 1


In [ ]:
# @title count path program
def count_paths(row, col, m, n):
    if row == m - 1 and col == n - 1:
        return 1

    if row >= m or col >= n:
        return 0

    right_path_count = count_paths(row, col + 1, m, n)
    down_path_count = count_paths(row + 1, col, m, n)

    return right_path_count + down_path_count

# Example usage:
m, n = 4, 5  # Dimensions of the grid
total_paths = count_paths(0, 0, m, n)

print(f"The total number of paths in a {m}x{n} grid is: {total_paths}")


The total number of paths in a 4x5 grid is: 35


In [ ]:
def count_paths(row, col):
    # Base case: if at the bottom-right corner, there is only one path
    if row == 0 and col == 0:
        return 1

    # If out of bounds, there are no paths
    if row < 0 or col < 0:
        return 0

    # Recursively count paths by moving right and down
    return count_paths(row - 1, col) + count_paths(row, col - 1)

# Example grid size (rows x cols)
rows, cols = 4, 5

# Count paths from top-left to bottom-right
result = count_paths(rows - 1, cols - 1)
print(f"Number of paths in a {rows}x{cols} grid: {result}")


Number of paths in a 4x5 grid: 35


Write a Python program that takes an array of integers as input and returns a new array that contains all the subsets of the original array.

In [ ]:
import numpy as np
def get_subset(arr):
    subset=[[]]
    for num in arr:
        for i in range(len(subset)):
            temp=subset[i]
            subset.append(temp+[num])
    return subset
arr=np.array([1,2,3,7])
subset=get_subset(arr)
for num in subset:
    print(num)


[]
[1]
[2]
[1, 2]
[3]
[1, 3]
[2, 3]
[1, 2, 3]
[7]
[1, 7]
[2, 7]
[1, 2, 7]
[3, 7]
[1, 3, 7]
[2, 3, 7]
[1, 2, 3, 7]


In [ ]:
def longest_common_subsequence(string1, string2):
    m,n = len(string1), len(string2)
    dp=[[0]*(m+1) for i in range(n+1)]
    for i in range(1,m+1):
        for j in range(1,n+1):
            if string1[i-1] == string2[j-1]:
                dp[i][j] = dp[i-1][j-1]+1
            else:
                dp[i][j] = max(dp[i-1][j],dp[i][j-1])
    return dp[-1][-1]

string1 = "ArrvGH"
string2 = "AEDFHR"
lcs_length = longest_common_subsequence(string1, string2)

print("The length of the longest common subsequence between", string1, "and", string2, "is:", lcs_length)


   0 1 2 3 4 5 <BR>
  A B C D G H <BR>
   A E D F H R<BR>

__A B C D G H <BR>


__0 0 0 0 0 0<BR>
A 1 1 1 1 1 1<BR>
E 1 1 1 1 1 1<BR>
D 1 1 1 2 2 2<BR>
F 1 1 1 2 2 2 <BR>
H 1 1 1 2 2 3<BR>
R 1 1 1 2 2 3<BR>

Write a Python program that takes an array of integers as input and returns the length of the longest increasing subsequence (not necessarily contiguous) in the array.

In [ ]:
def lon_inc_subseq(array):
    lis = [1]*len(array)
    for i in range(len(array)):
        for j in range(i):
            if array[j]<array[i]:
                lis[i]=max(lis[i],lis[j]+1)
    return lis[-1]
array = [10, 22, 9, 33, 21, 50, 41, 60]
lis_length = lon_inc_subseq(array)

print("The length of the longest increasing subsequence in", array, "is:", lis_length)

The length of the longest increasing subsequence in [10, 22, 9, 33, 21, 50, 41, 60] is: 5



This is the performance stages:
```
[10,22,9,33,21,50,41,60]
[1, 1, 1, 1, 1, 1, 1, 1]
[1, 2, 1, 1, 1, 1, 1, 1]
[1, 2, 1, 3, 1, 1, 1, 1]
[1, 2, 1, 3, 2, 4, 1, 1]
[1, 2, 1, 3, 2, 4, 4, 1]
[1, 2, 1, 3, 2, 4, 4, 5]
```




In [ ]:
# import numpy module
import numpy as np
# this function will display the all array elements by executing recursively
def display(arr,index):
    # base case if it reaches the last element
    if index==len(arr):
        return
    # print the current element and continue recursion
    else:
        print(arr[index])
        return display(arr,index+1)

#printing stopping condition
print("Enter q/Q to stop input:")
# empty list to store inputs from user
numbers=[]
# this loop will be executed until break encounter
while True:
    # receives a input
    num=int(input())
    # checks if it is 0 or not
    if num==0:
        break
    #append the value to numbers list
    else:
        numbers.append(num)
# convert list into array
arr=np.array(numbers)
# print the array by calling display function
print(display(arr,0))

In [ ]:
def find_paths(board, row=0, col=0):
    # Base case: If the current position is out of bounds or an obstacle, return 0
    if row >= len(board) or col >= len(board[0]) or board[row][col] == 1:
        return 0

    # Base case: If we reach the bottom-right corner, return 1 (one valid path found)
    if row == len(board) - 1 and col == len(board[0]) - 1:
        return 1

    # Recursive case: Move right and down, and sum the paths
    move_right = find_paths(board, row, col + 1)
    move_down = find_paths(board, row + 1, col)

    return move_right + move_down

# Example Usage
board = [
    [0, 0, 0, 0],
    [0, 0, 1, 0],
    [0, 1, 0, 1],
    [0, 0, 0, 0]
]

result = find_paths(board)
print(result)  # Output: 2


1


In [ ]:
# write a program such that all the values of list should sum of a given number; not less than nor greater than.
# print how many combinations are possible .

def print_combinations(target_sum, current_sum, start_num, combination):
    if current_sum == target_sum:
        print(combination)
    elif current_sum > target_sum:
        return
    else:
        for i in range(start_num, target_sum - current_sum + 1):
            print_combinations(target_sum, current_sum+i, i, combination+[i])


# Example usage:
print_combinations(4, 0, 1, [])

[1, 1, 1, 1]
[1, 1, 2]
[1, 3]
[2, 2]
[4]


Add elements of two arrays into a new array

In [ ]:
def add_arrays(arr1,arr2):
    if len(arr1)!= len(arr2):
        return "Both arrays must have same length"
    else:
        result=[]
        for i in range(len(arr1)):
            result.append(arr1[i]+arr2[i])
        return result
arr1 = [1, 2, 3, 4]
arr2 = [5, 6, 7, 8]
print(add_arrays(arr1, arr2))

arr3 = [1, 2, 3]
arr4 = [4, 5, 6, 7]
print(add_arrays(arr3, arr4))

[6, 8, 10, 12]
Both arrays must have same length


**NUMBER TO WORD CONVERSION**

In [ ]:
def number_to_words(num):
    if num == 0:
        return 'Zero'
    ones = ['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine']
    tens = ['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety']
    teens = ['Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen']
    thousands = ['','Thousand','Million','Billion','Trillion']

    def convert_below_1000(n):
        if n == 0:
            return ''
        elif n < 10:
            return ones[n]
        elif n < 20:                            #10,03,040, 40, 1003, 3040,
            return teens[n-10]
        elif n < 100:
            return tens[n//10] + ' ' + ones[n%10]
        else:
            return ones[n//100] + ' Hundred ' + convert_below_1000(n%100)

    words = ''
    i = 0
    while num > 0:
        if num % 1000 != 0:
            words = convert_below_1000(num % 1000) + thousands[i] + ' ' + words
        num //= 1000
        i += 1
    return words.strip()

# Example
num = 1003040
print(number_to_words(num))

OneMillion ThreeThousand Forty


In [ ]:
def n_digit_numbers_sum(n_digit, sum, num=''):
    if n_digit == 0:
        if sum == 0:
            return [num]
        else:
            return []
    res = []
    for i in range(10):
        if sum - i >= 0:
            res += n_digit_numbers_sum(n_digit-1, sum-i, num+str(i))
    return res
# Example
n = 3
s = 6
result=n_digit_numbers_sum(n, s)
print(result)
print("total=",len(result))

['006', '015', '024', '033', '042', '051', '060', '105', '114', '123', '132', '141', '150', '204', '213', '222', '231', '240', '303', '312', '321', '330', '402', '411', '420', '501', '510', '600']
total= 28


In [ ]:
# Remove adjacent duplicate characters from a string Using Recursion
def remove_adj_duplicate(s):
    result=[]
    for ch in s:
        if ch not in result or ch!=result[-1]:
            result.append(ch)
    return ''.join(result)
s='afdffdds'
print(remove_adj_duplicate(s))

In [ ]:
# Determine whether a string is a palindrome or not
def is_palindrome(s):
    s=s.lower()
    s=''.join(c for c in s if c.isalnum())
    return s==s[::-1]
# example usage
s1 = "A man, a plan, a canal: Panama"
s2 = "race a car"
print(is_palindrome(s1))
print(is_palindrome(s2))

In [ ]:
# Write a recursive function to find the sum of all possible subsequences of a given sequence.

def sub_sequence(seq):
    if not seq:
        return 0
    else:
        return sub_sequence(seq[1:])+ seq[0] + sub_sequence(seq[1:])

sub_sequence([1, 2])

In [ ]:
# What is the output of the following Python code?

def subsequence(inp, out):
    if len(inp) == 0:
        print(out)
        return
    subsequence(inp[1:], out)
    subsequence(inp[1:], out + inp[0])

subsequence("abc", "")




In [ ]:
# What is the output of the following Python code?

def find_data(arr, target, i=0):
    if i == len(arr):
        return False
    elif arr[i] == target:
        return True
    else:
        return find_data(arr, target, i+1)

arr = [1, 2, 3, 4, 5]
target = 6
print(find_data(arr, target))

In [ ]:
# What is the output of the following Python code?

def subsequences(arr, index, ans):
    if index == len(arr):
        print(ans)
        return
    subsequences(arr, index + 1, ans)
    subsequences(arr, index + 1, ans + str(arr[index]))

subsequences([1, 2, 3], 0, "")

In [ ]:
# What is the output of the following code snippet?

def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(7))
# time complexity: O(2^n).
# space complexity: O(n).

In [ ]:
# What is the output of the following Python code?

def find_data(arr, target):
    if len(arr) == 0:
        return False
    elif arr[len(arr)//2] == target:
        return True
    elif arr[len(arr)//2] < target:
        return find_data(arr[len(arr)//2+1:], target)
    else:
        return find_data(arr[:len(arr)//2], target)

arr = [1, 2, 3, 4, 5]
target = 3
print(find_data(arr, target))

# Time Complexity: O(log N)
# Space Complexity: O(log N)

Sure, I can simplify the paragraph for you:

An algorithm is like a recipe for a computer program, providing step-by-step instructions to solve a problem. It's widely used in computer science and other fields to automate tasks. In computing, it's like a treasure map guiding the way to complete a task, written in programming languages and executed by a computer.

Algorithms are essential in software development and used in applications like search engines, cryptography, artificial intelligence, and data analysis. They come in various types, such as sorting algorithms (arranging data) and search algorithms (finding data).

Think of algorithms as computing superheroes, making complex tasks simple and manageable, like a magical wand. Sorting and searching algorithms are fundamental, widely used tools in computer science, each with its advantages and disadvantages.

For example, bubble sort is a common sorting algorithm, and linear search efficiently finds data in a sorted list. These algorithms play a crucial role in making computer processes efficient and solving problems effectively.

In [ ]:
include_first = [[elements[0]] + rest for rest in generate_combinations(elements[1:], k-1)]


In [ ]:
def bubble_sort(arr):
    # storing length of the array
    n = len(arr)

    # Traverse through all array elements
    for i in range(n):

        # Last i elements are already in place
        for j in range(0, n-i-1):
            # Traverse the array from 0 to n-i-1
            # Swap if the element found is greater than the next element
            if arr[j] > arr[j+1] :
                arr[j], arr[j+1] = arr[j+1], arr[j]


arr = [15, 24, 27, 37, 11, 18, 6, 14]

bubble_sort(arr)
print("Sorted array is:")
for i in range(len(arr)):
    print("%d" %arr[i])

Sorted array is:
6
11
14
15
18
24
27
37


In [ ]:
# Define the linear search function that takes a list of data and a target value
def linear_search(data, target):
    # Loop over each element in the list of data
    for i in range(len(data)):
        # If the current element is equal to the target value, return the index of the element
        if data[i] == target:
            return i
    # If the target value is not found in the list of data, return -1
    return -1

# Get user input for the list of data and the target value
data = list(map(int, input("Enter the list of data, separated by spaces: ").split()))
target = int(input("Enter the target value: "))

# Call the linear search function with the list of data and the target value
index = linear_search(data, target)

# If the target value is found in the list of data, print a message with the index of the element
if index != -1:
    print(f"Target {target} found at index {index}")
# If the target value is not found in the list of data, print a message indicating it was not found
else:
    print(f"Target {target} not found in data")



Enter the list of data, separated by spaces: 1 2 3 4 5 6 8 9
Enter the target value: 2
Target 2 found at index 1


🤖💡🐍 Algorithm Fundamentals in Python:

* 📚 Algorithms are a set of instructions used to solve a problem or complete a task.

* 🧐 Types of algorithms include Brute Force Algorithm, Divide and Conquer Algorithm, Dynamic Programming Algorithm, Greedy Algorithm, and Backtracking Algorithm.

* 🤔 Searching algorithms include Linear Search Algorithms and Binary Search algorithms.

* 💭 Sorting algorithms include Bubble Sort Algorithm, Selection Sort Algorithm, Insertion Sort Algorithm, Merge Sort Algorithm, and Quick Sort Algorithm.

In [ ]:
# define a function selection_sort that takes an array as an input
def selection_sort(arr):
    # get the length of the array
    n = len(arr)

    # iterate through the array
    for i in range(n-1):
        # set the minimum index to the current index
        min_index = i

        # iterate through the remaining elements to find the minimum element
        for j in range(i+1, n):
            # if the current element is less than the minimum element, update the minimum index
            if arr[j] < arr[min_index]:
                min_index = j

        # swap the minimum element with the first unsorted element
        arr[i], arr[min_index] = arr[min_index], arr[i]

    # return the sorted array
    return arr

# define an array to be sorted
arr = [5, 3, 4, 1, 2]
print("Given array:", arr)

# call the selection_sort function and assign the sorted array to a new variable
sorted_arr = selection_sort(arr)

# print the sorted array
print("Sorted array is:", sorted_arr)



In [ ]:
def merge_sort(arr):
    # Check if the input array is only one element or empty, if so, return it
    if len(arr) <= 1:
        return arr

    # Divide the array into two halves
    mid = len(arr) // 2
    left_half = arr[:mid]
    right_half = arr[mid:]

    # Recursively call merge_sort on each half
    left_half = merge_sort(left_half)
    right_half = merge_sort(right_half)

    # Merge the two sorted halves
    i = j = 0  # Initialize two counters for the left and right halves
    merged_arr = []  # Create an empty list to store the merged array
    while i < len(left_half) and j < len(right_half):
        # Compare the first element of each half and add the smaller one to the merged array
        if left_half[i] < right_half[j]:
            merged_arr.append(left_half[i])
            i += 1
        else:
            merged_arr.append(right_half[j])
            j += 1

    # Append any remaining elements from the left or right halves to the merged array
    merged_arr += left_half[i:]
    merged_arr += right_half[j:]

    return merged_arr

arr = [64, 25, 12, 22, 11]
sorted_arr = merge_sort(arr)
print("Sorted array is:", sorted_arr)


In [ ]:
def insertion_sort(arr):
    n = len(arr)

    # Traverse through 1 to n
    for i in range(1, n):
        key = arr[i]  # Select the key value to be inserted at the correct position
        j = i - 1     # Set the previous element index

        # Move elements of arr[0..i-1], that are greater than key, to one position ahead of their current position
        while j >= 0 and key < arr[j]:
            arr[j+1] = arr[j]
            j -= 1

        arr[j+1] = key  # Insert the key value in its correct position

    return arr

arr = [64, 25, 12, 22, 11]
print("Given arrayL", arr)
sorted_arr = insertion_sort(arr)
print("Sorted array is:", sorted_arr)



In [ ]:
def quick_sort(arr):
    # Base case
    if len(arr) <= 1:
        return arr

    # Selecting the first element as pivot
    pivot = arr[0]

    # Initializing empty arrays to store elements
    # smaller than pivot and greater than pivot
    left = []
    right = []

    # Iterating over the elements in the array,
    # excluding the pivot
    for i in range(1, len(arr)):
        # If the element is smaller than pivot,
        # add it to the left array
        if arr[i] < pivot:
            left.append(arr[i])
        # Otherwise, add it to the right array
        else:
            right.append(arr[i])

    # Recursively sorting the left and right arrays,
    # and concatenating the sorted arrays with the pivot
    return quick_sort(left) + [pivot] + quick_sort(right)

# Testing the function
arr = [65, 33, 54, 1, 12]
print("Given array:", arr)
sorted_arr = quick_sort(arr)
print("Sorted array is:", sorted_arr)


Given array: [65, 33, 54, 1, 12]
Sorted array is: [1, 12, 33, 54, 65]


In [ ]:
# This function implements binary search algorithm to find the index of the target element in a given list of data.
def binary_search(data, target):
    left = 0   # Initialize the left pointer to the first index of the list.
    right = len(data) - 1   # Initialize the right pointer to the last index of the list.
    while left <= right:   # Loop until left pointer becomes greater than right pointer.
        mid = (left + right) // 2   # Calculate the middle index of the current search space.
        if data[mid] == target:   # If the middle element is the target element, return its index.
            return mid
        elif data[mid] < target:   # If the middle element is smaller than the target element, update the left pointer to mid+1.
            left = mid + 1
        else:   # If the middle element is larger than the target element, update the right pointer to mid-1.
            right = mid - 1
    return -1   # Target element was not found in the list, so return -1.

# Get user input for the list of data and the target value
data = list(map(int, input("Enter the list of data, separated by spaces: ").split()))
target = int(input("Enter the target value: "))

# Call the binary search function with the list of data and the target value
index = binary_search(data, target)

# If the target value is found in the list of data, print a message with the index of the element
if index != -1:
    print(f"Target {target} found at index {index}")
# If the target value is not found in the list of data, print a message indicating it was not found
else:
    print(f"Target {target} not found in data")


Enter the list of data, separated by spaces:   1 2 3 4 5 6 7 8 9       
Enter the target value: 6
Target 6 found at index 5


In [ ]:
# This function implements Interpolation search algorithm to find the index of the target element in a given list of data.
def interpolation_search(data, target):
    # Set the initial search range
    low = 0
    high = len(data) - 1

    # Continue searching while the search range is valid and the target value might be in the range
    while low <= high and target >= data[low] and target <= data[high]:
        # Calculate the estimated position of the target element using interpolation
        pos = low + ((high - low) // (data[high] - data[low])) * (target - data[low])

        # Check if the estimated position contains the target element
        if data[pos] == target:
            # Return the index of the target element
            return pos
        elif data[pos] < target:
            # If the estimated position is less than the target, search the upper half of the range
            low = pos + 1
        else:
            # If the estimated position is greater than the target, search the lower half of the range
            high = pos - 1

    # If the target element is not found, return -1
    return -1

# Get user input for the list of data and the target value
data = list(map(int, input("Enter the list of data, separated by spaces: ").split()))
target = int(input("Enter the target value: "))

# Call the interpolation search function with the list of data and the target value
index = interpolation_search(data, target)

# If the target value is found in the list of data, print a message with the index of the element
if index != -1:
    print(f"Target {target} found at index {index}")
# If the target value is not found in the list of data, print a message indicating it was not found
else:
    print(f"Target {target} not found in data")



Enter the list of data, separated by spaces: 2 5 9 15 26 35 57 69 84
Enter the target value: 35
Target 35 found at index 5


In [ ]:
1+(7//79)*(35-5)
8//82

0

###**Activity 1:**
Imagine you have a list of animals with their corresponding weights in pounds. You want to arrange the animals in ascending order based on their weight, starting from the lightest animal to the heaviest animal. For example, if you have a list of animals with the following weights: 🐘 elephant (5000 lbs), 🦒 giraffe (2000 lbs), 🦓 zebra (1000 lbs), and 🐰 rabbit (5 lbs), you want to arrange them in the following order: 🐰 rabbit, 🦓 zebra, 🦒 giraffe, 🐘 elephant.

Here's how you can use bubble sort to accomplish this task:

Create a list of animals and their corresponding weights in pounds.
Implement the bubble sort algorithm to sort the animals based on their weights.
Create a new list with the original animals assigned to the sorted weights.

In [ ]:
def bubble_sort_animals(animals,weights):
    n=len(weights)
    for i in range(n):
        for j in range(0,n-i-1):
            if weights[j]>weights[j+1]:
                weights[j],weights[j+1]=weights[j+1],weights[j]
                animals[j],animals[j+1]=animals[j+1],animals[j]


animals=['elephants','giraffe','zebra','rabbit']
weights=[5000,2000,1000,5]

# Apply bubble sort to arrange animals based on weights
bubble_sort_animals(animals, weights)

# Display the sorted list
for animal, weight in zip(animals, weights):
    print(f"{animal} ({weight} lbs)")

rabbit (5 lbs)
zebra (1000 lbs)
giraffe (2000 lbs)
elephants (5000 lbs)


###**Activity 2:**
🛒 You can use bubble sort to sort a list of groceries based on their prices. Imagine you have a shopping list 📝 of groceries 🍎🥦🍞 in no particular order, and you want to arrange the groceries in ascending order ⬆️ based on their prices 💰, starting from the cheapest item to the most expensive item.

Here's how you can use bubble sort to accomplish this task:

1️⃣ Use this given list of groceries and their prices. ('Eggs', 2.5), ('Milk', 3.0), ('Bread', 1.5), ('Apples', 0.75), ('Cheese', 5.0)

2️⃣ Implement the bubble sort algorithm to sort the groceries based on their prices.

3️⃣ Create a new list with the original groceries assigned to the sorted prices.

In [ ]:
def bubble_sort_groceries(groceries):
    n=len(groceries)
    for i in range(n):
        for j in range(0,n-i-1):
            if groceries[j][1]> groceries[j+1][1]:
                groceries[j+1],groceries[j]=groceries[j],groceries[j+1]
    print( groceries)


groceries=[('Eggs', 2.5), ('Milk', 3.0), ('Bread', 1.5), ('Apples', 0.75), ('Cheese', 5.0)]
bubble_sort_groceries(groceries)

[('Apples', 0.75),
 ('Bread', 1.5),
 ('Eggs', 2.5),
 ('Milk', 3.0),
 ('Cheese', 5.0)]

###**Activity 3:**
Imagine you have a bookshelf with a random assortment of books 📚 on it, and you're looking for a specific book with the title "The Great Gatsby" 🎩. You don't know where the book is located on the bookshelf 🤷‍♂️, so you'll need to search through each book 📖 until you find the one you're looking for.

Here's how you can use linear search to accomplish this task:

Create a list 📃 of books on the bookshelf 📚, including "The Great Gatsby" and other random books.
Implement the linear search algorithm to search through the list of books for "The Great Gatsby" 🔍.
Output the position of "The Great Gatsby" on the bookshelf 📚.

In [ ]:
def search_book(books,find_book):
    n=len(books)
    for i in range(n):
        if books[i]==find_book:
            return i+1
    return -1
books=["Whispers of the Forgotten",
"Ephemeral Echoes",
"The Enigma Cipher",
"Chronicles of Celestial Dreams",
"Midnight Serenade",
"The Great Gatsby",
"Spectral Visions",
"Echoes from the Abyss"]
print(books)
find_book="The Great Gatsby"
index=search_book(books,find_book)
if index!=-1:
    print(f"The book {books[index-1]} found in self {index}")
else:
    print("Sorry! We cannot found .")

['Whispers of the Forgotten', 'Ephemeral Echoes', 'The Enigma Cipher', 'Chronicles of Celestial Dreams', 'Midnight Serenade', 'The Great Gatsby', 'Spectral Visions', 'Echoes from the Abyss']
The book The Great Gatsby found in self 6


###**Activity 4:**
👫👬👭 You have a list of your friends' names, represented as strings. Write a program that uses linear search to find the friend with the shortest name.

📝 Create a list of your friends' names, e.g. : ["Alice", "Bob", "Charlie", "David", "Eve", "Frank"]

💻 Implement a linear_search function that takes a list of names as a parameter and returns the name with the shortest length.

🔍 Call the linear_search function with the list of friends' names as an argument.

📣 Output the name of the friend with the shortest name using a print statement.

👨‍💻 Happy coding!

In [ ]:
def shortest_name(friends):
    short=friends[0]
    for i in range(len(friends)):
        if len(friends[i])<len(short):
            short=friends[i]
    print(short)
friends=["Alice", "Bob", "ie", "David", "Eve", "Frank"]
shortest_name(friends)

ie


###**Activity 5:**
Imagine you have a list of candies with their corresponding sugar content in grams. You want to arrange the candies in descending order based on their sugar content, starting from the candy with the most sugar to the candy with the least sugar. For example, if you have a list of candies with the following sugar content: 🍭 lollipop (30 g), 🍬 gumdrop (20 g), 🍫 chocolate (15 g), and 🍮 jelly bean (10 g), you want to arrange them in the following order: 🍭 lollipop, 🍬 gumdrop, 🍫 chocolate, 🍮 jelly bean.

Here's how you can use merge sort to accomplish this task:

Create a list of candies and their corresponding sugar content in grams.

Implement the merge sort algorithm to sort the candies based on their sugar content.

Create a new list with the original candies assigned to the sorted sugar content.

In [ ]:
def merge_sort_candy(candies):
    if len(candies)<=1:
        return candies
    mid=len(candies)//2
    left=candies[:mid]
    right=candies[mid:]

    left=merge_sort_candy(left)
    right=merge_sort_candy(right)

    i=j=0
    merge_candy=[]
    while i < len(left) and j < len(right):
        if left[i][1] > right[j][1]:
            merge_candy.append(left[i])
            i += 1
        else:
            merge_candy.append(right[j])
            j += 1
    merge_candy.extend(left[i:])
    merge_candy.extend(right[j:])
    return merge_candy

candies=[('lollopop',30),('chocolate',15),('gumdrop',20),('jelly bean',10)]
print(merge_sort_candy(candies))



[('lollopop', 30), ('gumdrop', 20), ('chocolate', 15), ('jelly bean', 10)]


**Time and Space Complexities of Searching and Sorting Algorithms**

### Searching Algorithms:

| Algorithm       | Time Complexity           | Space Complexity         |
|-----------------|---------------------------|--------------------------|
| Linear Search   | O(n)                      | O(1)                     |
| Binary Search   | O(log n)                  | O(1)                     |
| Hashing         | O(1) (Average Case)       | O(n)                     |

### Sorting Algorithms:

| Algorithm       | Time Complexity           | Space Complexity         |
|-----------------|---------------------------|--------------------------|
| Bubble Sort     | O(n^2) (worst, avg), O(n) (best)| O(1)                 |
| Selection Sort  | O(n^2)                    | O(1)                     |
| Insertion Sort  | O(n^2) (worst, avg), O(n) (best)| O(1)                 |
| Merge Sort      | O(n log n)                | O(n)                     |
| Quick Sort      | O(n^2) (worst), O(n log n) (avg), O(n log n) (best with good pivot)| O(log n) (avg), O(n) (worst)|
| Heap Sort       | O(n log n)                | O(1)                     |
| Counting Sort   | O(n + k)                  | O(k)                     |
| Radix Sort      | O(d * (n + k))            | O(n + k)                 |

These complexities provide an overview of the time and space requirements for each algorithm. Remember that the actual performance can depend on various factors, and these are generalizations.

In [ ]:
# How can you efficiently find the longest common prefix among a set of strings?
def longest_common_prefix(strings):
    if not strings:
        return ""

    # Start with the first string as the initial common prefix
    prefix = strings[0]

    for string in strings[1:]:
        i = 0
        while i < len(prefix) and i < len(string) and prefix[i] == string[i]:
            i += 1

        # Update the common prefix
        prefix = prefix[:i]

        # If the common prefix becomes empty, no need to check further
        if not prefix:
            break

    return prefix

# Example usage:
string_list = ["apple", "appetizer", "applicable"]
result = longest_common_prefix(string_list)
print(result)


app


Write a memoized version of the Fibonacci function.

In [ ]:
fibonacci_cache = {}

def fibonacci_memo(n):
    if n in fibonacci_cache:
        return fibonacci_cache[n]
    elif n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        result = fibonacci_memo(n-1) + fibonacci_memo(n-2)
        fibonacci_cache[n] = result
        return result
print(fibonacci_memo(6))

8


In [ ]:
Find the Missing Number in an Array