<a href="https://colab.research.google.com/github/manishaachary13/Alma_study/blob/main/note_data_wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('happy coding')

happy coding


🔍 Data wrangling involves cleaning, transforming, and preparing raw data for analysis, which can be computationally intensive and time-consuming.

💻 Code optimization is the process of improving the performance of code by reducing its resource usage, improving its efficiency, and making it more maintainable.

🌟 By optimizing their code for data wrangling, developers can reduce the time and resources required to perform tasks such as cleaning, transforming, and merging data.

📈 Code optimization can also improve the scalability of data wrangling tasks, allowing data analysts and data scientists to work with larger datasets more efficiently.

🚀 Some techniques for code optimization in data wrangling include:

1. Vectorization, which involves performing operations on entire arrays or matrices of data rather than on individual elements

2. Caching, which involves storing the results of computationally intensive operations in memory for faster access

3. Parallelization, which involves splitting up a task into smaller, independent parts that can be executed simultaneously on multiple processors or cores

4. Concurrency, which involves the ability to execute multiple tasks or processes simultaneously, either on the same processor/core (using techniques such as threads or asyncio) or across multiple processors/cores (using techniques such as multiprocessing or distributed computing).


In [ ]:
# calculate dot product of two array using normal way
import numpy as np
a=np.array([1,2,3])
b=np.array([3,2,1])
dot_product=0
for i in range(len(a)):
    dot_product+=a[i] * b[i]
dot_product

10

In [ ]:
# calculate dot prosuct using built-in function
dot_product=np.dot(a,b)
dot_product

10

In [ ]:
# caching
from joblib import Memory
mem=Memory(location='cache')
@mem.cache
def calc_mean(arr):
    print('calculating mean.....')
    return sum(arr)/len(arr)


# define a list of numbers to use for testing
my_list = [1, 2, 3, 4, 5]
# call the function the first time, which will calculate the mean and cache the result
result1 = calc_mean(my_list)

# call the function again with the same argument, which will retrieve the cached result instead of recalculating it
result2 = calc_mean(my_list)

# print the results
print(result1)  # should be 3.0
print(result2)  # should also be 3.0, and the "Calculating mean..." message should not be printed


________________________________________________________________________________
[Memory] Calling __main__--content-<ipython-input-e2b81c55e9b0>.calc_mean...
calc_mean([1, 2, 3, 4, 5])
calculating mean.....
________________________________________________________calc_mean - 0.0s, 0.0min
3.0
3.0


In [ ]:
pip install pandarallel


  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 1.4 MB/s eta 0:00:00
  Created wheel for pandarallel: filename=pandarallel-1.6.5-py3-none-any.whl size=16672 sha256=d143e786b0b07b0f274c6949a037b3a72f182e82269b4b2f037220598fbdaf1e
  Stored in directory: /root/.cache/pip/wheels/50/4f/1e/34e057bb868842209f1623f195b74fd7eda229308a7352d47f
Successfully built pandarallel


In [ ]:
import pandas as pd
from pandarallel import pandarallel

# initialize pandarallel
pandarallel.initialize()

# create a sample dataframe
df = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [6, 7, 8, 9, 10]})

# define a function to apply to each row of the dataframe
def my_func(row):
    return row['A'] + row['B']

# use pandarallel to apply the function to each row in parallel
result = df.parallel_apply(my_func, axis=1)

# print the result
print(result)


INFO: Pandarallel will run on 1 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
0     7
1     9
2    11
3    13
4    15
dtype: int64


concurrency is about executing multiple tasks simultaneously on the same processor or core, while parallelization is about executing multiple tasks simultaneously on multiple processors or cores. Both techniques can be used to achieve efficient use of computer resources, but they have different advantages and limitations depending on the task at hand.

In [ ]:
import threading
import time

def task(name):
    print(f'Starting task {name} ')
    time.sleep(2) # simulate some work
    print(f'Ending task {name} ')

if __name__ == '__main__':
    # Create 5 threads
    threads = [threading.Thread(target=task, args=(i,)) for i in range(5)]

    # Start the threads
    for t in threads:
        t.start()

    # Wait for all threads to complete
    for t in threads:
        t.join()

    print('All tasks completed')


Starting task 0 
Starting task 1 
Starting task 2 
Starting task 3 
Starting task 4 
Ending task 0 
Ending task 1 
Ending task 2 
Ending task 4 
Ending task 3 
All tasks completed


In [ ]:
import pandas as pd

# Create a sample data frame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Multiply each element in column A by 2 using vectorization
df['A'] = df['A'] * 2

# Print the updated data frame
print(df)

   A  B
0  2  4
1  4  5
2  6  6


In [ ]:
 # Group the data frame by year and item and extract a number of stats from each group
# imdb_df.groupby(['release_year', 'original_language'],as_index=False).agg({'runtime':"mean",'revenue': "sum",'imdb_id':"count"}).sort_values(by='release_year').rename(columns ={'runtime':'avg_runtime','revenue':'total_revenue','imdb_id':'num_movies'})


### what is data munging?
Data Munging, commonly referred to as Data Wrangling, is the cleaning and transforming of one type of data to another type to make it more appropriate into a processed format. Data wrangling involves processing the data in various formats and analyzes and get them to be used with another set of data and bringing them together into valuable insights.


Code optimization, in simple terms, means reducing the number of operations to execute any task while producing the correct results.

In [ ]:
'''
Optimizing Codes - Apply Function
'''

# importing required libraries
import pandas as pd
import numpy as np
import time
import math

data = pd.read_csv('train_.csv')

# print the head
print(data.head())

# calculate Number of Words using Dataframe iterrows

print('\n\nUsing Iterrows\n\n')
start_time = time.time()
data_1 = data.copy()
n_words = []
for i, row in data_1.iterrows():
  n_words.append(len(row['tweet'].split()))

data_1['n_words'] = n_words

print(data_1[['id','n_words']].head())
end_time = time.time()

print('\nTime taken to calculate No. of Words by iterrows :',
(end_time-start_time),'seconds')


# Calculate Number of Words using numpy array

print('\n\nUsing Numpy Arrays\n\n')
start_time = time.time()
data_2 = data.copy()
n_words_2 = []

for row in data_2.values:
  n_words_2.append(len(row[2].split()))

data_2['n_words'] = n_words_2
print(data_2[['id','n_words']].head())

end_time = time.time()
print('\nTime taken to calculate No. of Words by numpy array : ',
(end_time-start_time),'seconds')


# Calculate Number of Words by apply method:
print('\n\nUsing Apply Method\n\n')
start_time = time.time()
data_3 = data.copy()


data_3['n_words'] = data_3['tweet'].apply(lambda x : len(x.split()))
print(data_3[['id','n_words']].head())

end_time = time.time()
print('\nTime taken to calculate No. of Words by Apply Method : ',
(end_time-start_time),'seconds')

FileNotFoundError: ignored

In [ ]:
from joblib import Memory
import time
import pandas as pd
mem=Memory(location='cache')
@mem.cache
def thrice(num):
    print("Program is running...")
    return num*3
nums=pd.DataFrame({'a':[1,2,3,4,5],'b':[5,4,3,2,1]})
temp=nums['a']
result=thrice(nums['a'])
result2=thrice(nums['b'])
print(result)
print(result)
print(result2)

________________________________________________________________________________
[Memory] Calling __main__--content-<ipython-input-ec58a4e3b815>.thrice...
thrice(0    1
1    2
2    3
3    4
4    5
Name: a, dtype: int64)
Program is running...
___________________________________________________________thrice - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-<ipython-input-ec58a4e3b815>.thrice...
thrice(0    5
1    4
2    3
3    2
4    1
Name: b, dtype: int64)
Program is running...
___________________________________________________________thrice - 0.0s, 0.0min
0     3
1     6
2     9
3    12
4    15
Name: a, dtype: int64
0     3
1     6
2     9
3    12
4    15
Name: a, dtype: int64
0    15
1    12
2     9
3     6
4     3
Name: b, dtype: int64


Can you use Pandarallel to parallelize a Pandas apply operation on a DataFrame in Google Colab?

**Instructions:**

1. Create a Pandas DataFrame containing a list of integers.

2. Define a custom function that squares a number.

3. Use Pandas apply method to apply the custom function to each element of the DataFrame.

4. Parallelize the apply operation using Pandarallel.

5. Compare the execution times of the apply operation with and without Pandarallel.

**Hints:**

1. Use the "pandarallel" library to enable parallel processing.

2. Use the "apply" method with the "parallel=True" option to parallelize the apply operation.


In [ ]:
import pandas as pd
import time
from pandarallel import pandarallel
pandarallel.initialize()
nums=[1,2,3,4,5]
nums=pd.DataFrame({'numbers':nums})
def sq(num):
    return num**2

s_time=time.time()
nums['parallel']=nums['numbers'].parallel_apply(sq)
print('time1=',time.time()-s_time)
s_time=time.time()
nums['without parallel']=nums['numbers'].apply(sq)
print('time2=',time.time())
nums


INFO: Pandarallel will run on 1 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
time1= 0.06117820739746094
time2= 1703333751.2916856


numbers  parallel  without parallel
0        1         1                 1
1        2         4                 4
2        3         9                 9
3        4        16                16
4        5        25                25

In [ ]:
# Import numpy
import numpy as np
list=[1,5,26,2,17]
    # Convert the list to a numpy array
numlist=np.array(list)


    # Find the elements that are greater than or equal to 5
new_array=np.where(numlist >= 5, np.power(numlist,2), numlist)

    # Square the selected elements


    # Return the modified array as a list
new_array
    #test case

array([  1,  25, 676,   2, 289])

In [ ]:
import numpy as np
A=np.round(10*np.random.rand(5,8))
A
# here axis 0 means sorting will be applicable on colum wise and axis 1 means row wise
A.sort(axis=0)
A


array([[ 2.,  4.,  1.,  2.,  0.,  3.,  1.,  1.],
       [ 2.,  6.,  3.,  3.,  7.,  7.,  4.,  4.],
       [ 3.,  7.,  7.,  8.,  7.,  7.,  6.,  5.],
       [ 8.,  7.,  7.,  8.,  8.,  8.,  8.,  5.],
       [ 8.,  9.,  9.,  9.,  9., 10., 10.,  6.]])

In [ ]:
A[[2,3,4]]
# this will print the particular index position values.
# if the variable is matrix then it will perform on row-wise else on each values

array([[ 3.,  7.,  7.,  8.,  7.,  7.,  6.,  5.],
       [ 8.,  7.,  7.,  8.,  8.,  8.,  8.,  5.],
       [ 8.,  9.,  9.,  9.,  9., 10., 10.,  6.]])

In [ ]:
# syntax: A[index_array]
x=A[0]
# x[[1,4,5]]
x[[True, True, False, False, True, False,True,True]]
# the above line will perform boolean operation. this will return the array value whose boolean value is True only
A[A>5]
A[(A<8) & (A>5)]



array([6., 7., 7., 7., 7., 7., 7., 6., 7., 7., 6.])

### Difference between & and 'and' operator
    The symbols(&, | and ~) are used on arrays and it returns boolean values;
    while the wording format of these operators(and, or, not) are used on only single objects.



In [ ]:
print(A)
A=A+2
print(A)

[[ 2.  4.  1.  2.  0.  3.  1.  1.]
 [ 2.  6.  3.  3.  7.  7.  4.  4.]
 [ 3.  7.  7.  8.  7.  7.  6.  5.]
 [ 8.  7.  7.  8.  8.  8.  8.  5.]
 [ 8.  9.  9.  9.  9. 10. 10.  6.]]
[[ 4.  6.  3.  4.  2.  5.  3.  3.]
 [ 4.  8.  5.  5.  9.  9.  6.  6.]
 [ 5.  9.  9. 10.  9.  9.  8.  7.]
 [10.  9.  9. 10. 10. 10. 10.  7.]
 [10. 11. 11. 11. 11. 12. 12.  8.]]


In [ ]:
# np.hstack, vstack, sort
arr=np.arange(6).reshape(3,2)
arr
c=np.hstack(A)
c

array([ 4.,  6.,  3.,  4.,  2.,  5.,  3.,  3.,  4.,  8.,  5.,  5.,  9.,
        9.,  6.,  6.,  5.,  9.,  9., 10.,  9.,  9.,  8.,  7., 10.,  9.,
        9., 10., 10., 10., 10.,  7., 10., 11., 11., 11., 11., 12., 12.,
        8.])

In [ ]:
# in this we used the permutation with arange and sorting
arr1=np.random.permutation(np.arange(10))
print(arr1)
np.sort(arr1)[::-1]

[8 1 9 5 6 2 7 3 0 4]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# the purpose of this code is to figure out the fast of numpy functions with normal py function
arr2=np.random.rand(1000)
%timeit sum(arr2)
%timeit np.sum(arr2)
# obviously numpy is faster

127 µs ± 42.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
5.45 µs ± 597 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit
def mysum(n):
    s=0
    for i in n:
        s+=n
    return s


In [ ]:
# prompt: armstrong number

num = int(input("Enter a number: "))
sum = 0
temp = num
while temp > 0:
    digit = temp % 10
    sum += digit ** 3
    temp //= 10
if num == sum:
    print(f"{num} is an Armstrong number")
else:
    print(f"{num} is not an Armstrong number")


Enter a number: 22
22 is not an Armstrong number


In [ ]:
table=pd.DataFrame([{'a':1,'b':2},{'b':1,'c':3}])
table
table.fillna(0)
# table.dropna()

a  b    c
0  1.0  2  0.0
1  0.0  1  3.0

In [ ]:
import json as js
# open jSON FILE , loaD THEN PRINT

with open('/content/cache/employee.json') as f:
    employee=js.load(f)
print(employee)
employee[0]

[{'id ': 1, 'name ': 'john', 'age ': 20, 'gender': 'male', 'department': 'hr', 'salary': 500000}, {'id ': 2, 'name ': 'jane', 'age ': 23, 'gender': 'female', 'department': 'marketing', 'salary': 600000}, {'id ': 3, 'name ': 'joey', 'age ': 23, 'gender': 'male', 'department': 'it', 'salary': 300000}, {'id ': 4, 'name ': 'sarah', 'age ': 25, 'gender': 'female', 'department': 'hr', 'salary': 450000}, {'id ': 5, 'name ': 'rose', 'age ': 28, 'gender': 'male', 'department': 'hr', 'salary': 700000}, {'id ': 6, 'name ': 'bing', 'age ': 29, 'gender': 'male', 'department': 'finance', 'salary': 800000}, {'id ': 7, 'name ': 'rach', 'age ': 41, 'gender': 'female', 'department': 'it', 'salary': 600000}, {'id ': 8, 'name ': 'monica', 'age ': 23, 'gender': 'female', 'department': 'marketing', 'salary': 7000000}, {'id ': 9, 'name ': 'pheebe', 'age ': 35, 'gender': 'female', 'department': 'it', 'salary': 4000000}]


{'id ': 1,
 'name ': 'john',
 'age ': 20,
 'gender': 'male',
 'department': 'hr',
 'salary': 500000}

In [ ]:
# accessing json file data
data=employee[5]
name=data['name ']
salary=data['salary']
print(f"name:{name}, salary:{salary}")

name:bing, salary:800000


In [ ]:
data2=employee[2]
data2['age ']=25




```
Certainly! Let's go through each example line by line:

### Example 1: Read JSON File
```python
import json

# Read JSON file
with open('example.json', 'r') as file:
    data = json.load(file)

print(data)
```

- `import json`: Imports the built-in `json` module for working with JSON data.
- `with open('example.json', 'r') as file:`: Opens the JSON file named 'example.json' in read mode. The `with` statement is used to ensure that the file is properly closed after reading.
- `data = json.load(file)`: Loads the JSON data from the file into a Python dictionary. The `json.load` function reads the file and parses its contents into a Python data structure.
- `print(data)`: Prints the loaded data, which is now a Python dictionary.

### Example 2: Write to JSON File
```python
import json

# Data to be written to the JSON file
data = {'name': 'John', 'age': 30, 'city': 'New York'}

# Write to JSON file
with open('output.json', 'w') as file:
    json.dump(data, file, indent=2)
```

- `data = {'name': 'John', 'age': 30, 'city': 'New York'}`: Creates a Python dictionary with sample data.
- `with open('output.json', 'w') as file:`: Opens a new JSON file named 'output.json' in write mode.
- `json.dump(data, file, indent=2)`: Writes the dictionary `data` to the file in JSON format. The `indent=2` argument adds indentation to make the JSON file more human-readable.

### Example 3: Modify JSON Data
```python
import json

# Read JSON file
with open('example.json', 'r') as file:
    data = json.load(file)

# Modify data
data['age'] = 31

# Write modified data back to JSON file
with open('example.json', 'w') as file:
    json.dump(data, file, indent=2)
```

- This example builds upon Example 1. It reads the JSON file, modifies the value of the 'age' key in the loaded dictionary, and then writes the modified data back to the same file.

### Example 4: Pretty Print JSON
```python
import json

# Read JSON file
with open('example.json', 'r') as file:
    data = json.load(file)

# Pretty print JSON
print(json.dumps(data, indent=2))
```

- This example reads the JSON file, loads it into a Python dictionary, and then uses `json.dumps` to convert the dictionary back to a JSON-formatted string with indentation (`indent=2`). Finally, it prints the pretty-printed JSON.

### Example 5: Check if Key Exists
```python
import json

# Read JSON file
with open('example.json', 'r') as file:
    data = json.load(file)

# Check if a key exists
if 'age' in data:
    print(f"Age: {data['age']}")
else:
    print("Age key does not exist.")
```

- This example checks whether the key 'age' exists in the loaded JSON data. If it does, it prints the value associated with the 'age' key; otherwise, it prints a message indicating that the key does not exist.

### Example 6: Iterate Over JSON Array
```python
import json

# Read JSON file with an array
with open('example_array.json', 'r') as file:
    data_array = json.load(file)

# Iterate over array elements
for item in data_array:
    print(item)
```

- This example reads a JSON file containing an array of objects. It loads the data into a Python list (`data_array`) and then iterates over each element in the list, printing each element.

### Example 7: Convert JSON to String and Vice Versa
```python
import json

# Data as a dictionary
data_dict = {'name': 'Alice', 'age': 25}

# Convert dictionary to JSON string
json_string = json.dumps(data_dict)

# Convert JSON string to dictionary
data_dict_from_json = json.loads(json_string)
```

- `data_dict = {'name': 'Alice', 'age': 25}`: Creates a Python dictionary.
- `json_string = json.dumps(data_dict)`: Converts the dictionary to a JSON-formatted string using `json.dumps`.
- `data_dict_from_json = json.loads(json_string)`: Converts the JSON-formatted string back to a Python dictionary using `json.loads`.

These examples cover various operations you can perform with JSON files in Python, from reading and writing to modifying data and checking for key existence. Adjustments can be made based on specific requirements and the structure of your JSON data.
```



In [ ]:
import json

# modify data
with open('/content/cache/employee.json','r') as f:
    data=json.load(f)


with open('/content/cache/employee.json','w') as f:
    json.dump(data,f,indent=2)
# print(json.dumps(data,indent=2))
for item in data:
    print(item)

if 'gender ' in data[4]:
    print('True')
else:
    print(False)

{'id ': 1, 'name ': 'john', 'age ': 20, 'gender': 'male', 'department': 'hr', 'salary': 500000}
{'id ': 2, 'name ': 'jane', 'age ': 23, 'gender': 'female', 'department': 'marketing', 'salary': 600000}
{'id ': 3, 'name ': 'joey', 'age ': 23, 'gender': 'male', 'department': 'it', 'salary': 300000}
{'id ': 4, 'name ': 'sarah', 'age ': 25, 'gender': 'female', 'department': 'hr', 'salary': 450000}
{'id ': 5, 'name ': 'rose', 'age ': 28, 'gender': 'male', 'department': 'hr', 'salary': 700000}
{'id ': 6, 'name ': 'bing', 'age ': 29, 'gender': 'male', 'department': 'finance', 'salary': 800000}
{'id ': 7, 'name ': 'rach', 'age ': 41, 'gender': 'female', 'department': 'it', 'salary': 600000}
{'id ': 8, 'name ': 'monica', 'age ': 23, 'gender': 'female', 'department': 'marketing', 'salary': 7000000}
{'id ': 9, 'name ': 'pheebe', 'age ': 35, 'gender': 'female', 'department': 'it', 'salary': 4000000}
False


In [ ]:
import xml.etree.ElementTree as et
# parse the path
tree=et.parse('/content/sample_data/author.xml')
# get root element
root=tree.getroot()
print(root)
print(root.tag)

# access the elements and attributed
for book in root.iter('book'):
    # title=book.find('title').text
    # pub=book.find('publisher').text
    print(book.tag)
# print(title)
# print(pub)

<Element 'books' at 0x7e802623b010>
books
book
book
book


In [ ]:
book2=root.find("./book[@id='2']")
if book2 is not None:
    print(book2.find('author').text)
    print(book2.find('title').text)

Harper Lee
To Kill a Mockingbird


In [ ]:
# Create a new book element
new_book = et.Element('book', {'id': '4'})
title = et.SubElement(new_book, 'title')
title.text = 'The Great Gatsby'
author = et.SubElement(new_book, 'author')
author.text = 'F. Scott Fitzgerald'
year = et.SubElement(new_book, 'year')
year.text = '1925'
publisher = et.SubElement(new_book, 'publisher')
publisher.text = "Charles Scribner's Sons"

# Add the new book element to the root element
root.append(new_book)

# Write the updated XML file
tree.write('books.xml')

In [ ]:
book4=root.find("./book[@id='4']")
if book4 is not None:
    print(book4.find('author').text)
    print(book4.find('title').text)

F. Scott Fitzgerald
The Great Gatsby


In [ ]:

# Find the book element with an id of 2
book_to_remove = root.find("./book[@id='2']")

# Remove the book element from the root element
root.remove(book_to_remove)

# Save the updated XML file
tree.write('books.xml')

TypeError: ignored

In [ ]:
book4=root.find("./book[@id='2']")
if book4 is not None:
    print(book4.find('author').text)
    print(book4.find('title').text)
else:
    print("so.. sad")

so.. sad


1️⃣ Print the first 5 rows of the data to get a quick overview of the information.

2️⃣ Find the mean salary for each gender in the company. This will help you understand if there is a gender pay gap in the company.

3️⃣ Calculate the budget allocated to each department by summing up the salaries of all employees in that department. This information will be useful for the management to make informed decisions about budget allocation and resource planning.

In [ ]:
import pandas as pd
import numpy as np

# Create a DataFrame with missing values
data = {'A': [1, 2, np.nan, 4, 5],
        'B': [10, np.nan, 30, 40, 50]}

df = pd.DataFrame(data)

# Interpolate missing values using linear interpolation
df.interpolate(method='quadratic', inplace=True)

print(df)


ValueError: ignored